# Generated by Django 3.2 on 2022-04-23 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('karaites', '0002_search_trigger'),
    ]
    migration = '''
        CREATE MATERIALIZED VIEW autocomplete_view AS
        SELECT id, word_en, word_count, classification
        FROM karaites_autocomplete
        ORDER BY  classification, word_en, word_count;
        
        DROP INDEX IF EXISTS autocomplete_en;
        CREATE INDEX autocomplete_en ON karaites_autocomplete USING GIN (to_tsvector('english', word_en));
        
        REFRESH MATERIALIZED VIEW autocomplete_view;
    '''

    reverse_migration = '''
        DROP MATERIALIZED VIEW  IF EXISTS autocomplete_view
    '''
    operations = [
        migrations.RunSQL(migration, reverse_migration)
    ]
