# Generated by Django 3.2 on 2022-04-25 13:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0003_autocomplete_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invertedindex',
            options={'ordering': ('rank',), 'verbose_name_plural': 'Inverted index'},
        ),
        migrations.AddField(
            model_name='invertedindex',
            name='rank',
            field=models.FloatField(db_index=True, default=0, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='invertedindex',
            name='count_by_document',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None, verbose_name='Count by document'),
        ),
        migrations.AlterField(
            model_name='invertedindex',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None, verbose_name='List of documents'),
        ),
    ]
