# Generated by Django 3.2 on 2022-04-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0004_auto_20220425_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invertedindex',
            name='rank',
            field=models.FloatField(db_index=True, default=0, verbose_name='-Rank'),
        ),
    ]
