# Generated by Django 3.2 on 2022-04-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0007_auto_20220426_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='index_lang',
            field=models.BooleanField(default=True),
        ),
    ]
