# Generated by Django 4.0 on 2022-05-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0009_auto_20220511_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulltextsearch',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='fulltextsearchhebrew',
            name='delete',
        ),
    ]
