# Generated by Django 4.0 on 2022-05-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0010_remove_fulltextsearch_delete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=40, verbose_name='English word')),
            ],
            options={
                'verbose_name_plural': 'English words',
            },
        ),
    ]
