# Generated by Django 4.0 on 2022-05-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0013_misspelledword_alter_englishword_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misspelledword',
            name='corrected_word',
        ),
        migrations.AddField(
            model_name='misspelledword',
            name='correct_word',
            field=models.CharField(db_index=True, default='', max_length=40, verbose_name='Correct word'),
            preserve_default=False,
        ),
    ]
