# Generated by Django 4.0.4 on 2022-06-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0022_remove_karaitesbookdetails_song_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_level', models.CharField(max_length=100, verbose_name='First level')),
                ('second_level', models.CharField(max_length=100, verbose_name='Second level')),
            ],
            options={
                'verbose_name_plural': 'Book Classification',
                'ordering': ('first_level', 'second_level'),
            },
        ),
    ]
