# Generated by Django 4.0.4 on 2022-06-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0023_bookclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookClassificationFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_level', models.CharField(max_length=50, verbose_name='First level')),
            ],
            options={
                'verbose_name_plural': 'Book Classification first',
                'ordering': ('first_level',),
            },
        ),
        migrations.CreateModel(
            name='BookClassificationSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_level', models.CharField(max_length=50, verbose_name='Second level')),
            ],
            options={
                'verbose_name_plural': 'Book Classification Second',
                'ordering': ('second_level',),
            },
        ),
        migrations.DeleteModel(
            name='BookClassification',
        ),
    ]
