# Generated by Django 4.0.4 on 2022-06-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0025_alter_bookclassificationfirst_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100, verbose_name='Song Title')),
                ('song_file', models.FileField(upload_to='songs/', verbose_name='Song File')),
            ],
            options={
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.RemoveField(
            model_name='karaitesbookdetails',
            name='songs_list',
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='css_class',
            field=models.CharField(default='', help_text='This field is used to inform the class to add to the book', max_length=100, verbose_name='CSS class'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='buy_link',
            field=models.CharField(default='', help_text='This field is used to inform the buy link of the book', max_length=255, verbose_name='Buy link'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='columns',
            field=models.IntegerField(default=0, help_text='This field is used to inform the number of columns in the book', verbose_name='Columns'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='columns_order',
            field=models.CharField(default='', help_text='This field is used to inform the order of columns in the book', max_length=10, verbose_name='Columns order'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='direction',
            field=models.CharField(choices=[('rtl', 'rtl'), ('ltr', 'ltr')], default='rtl', help_text='This field is used to inform the direction of the text in the book', max_length=3, verbose_name='Text Direction'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='index_lang',
            field=models.BooleanField(default=True, verbose_name='Index transliteration'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='introduction',
            field=models.TextField(default='', editable=False, help_text='This field is used to store the introduction of the book', verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='multi_tables',
            field=models.BooleanField(default=False, help_text='This field is used to inform that book has more than one table', verbose_name='Multi tables'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='remove_class',
            field=models.CharField(default='', help_text='This field is used to inform the class to remove from the book', max_length=100, verbose_name='Remove class'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='remove_tags',
            field=models.CharField(default='', help_text='This field is used to inform the tags to remove from the book', max_length=100, verbose_name='Remove tags'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='table_book',
            field=models.BooleanField(default=False, help_text='This field is used to inform that book is a html table', verbose_name='Table Book'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='toc_columns',
            field=models.CharField(default='', help_text='This field is used to inform the order of columns in the table of contents', max_length=10, verbose_name='TOC Columns'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='songs',
            field=models.ManyToManyField(to='karaites.songs'),
        ),
    ]
