# Generated by Django 4.0.4 on 2022-06-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0026_songs_remove_karaitesbookdetails_songs_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='intro',
            field=models.BooleanField(default=False, verbose_name='Book has Introduction'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='toc',
            field=models.BooleanField(default=False, verbose_name='Book has TOC'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='css_class',
            field=models.CharField(choices=[('', 'None'), ('simple', 'Simple'), ('simple-3-4', 'Simple 3 4'), ('special', 'Special'), ('special-1', 'Special 1'), ('sefer-extra', 'Sefer Extra')], help_text='This field is used to inform the class to add to the book', max_length=100, verbose_name='CSS class'),
        ),
    ]
