# Generated by Django 4.0.4 on 2022-06-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0027_karaitesbookdetails_intro_karaitesbookdetails_toc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='book_intro_source',
            field=models.FileField(blank=True, default='', help_text='This field is used to store the source of the book introduction', upload_to='books/', verbose_name='Book Intro Source'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='book_source',
            field=models.FileField(default='', help_text='This field is used to store the source of the book', upload_to='books/', verbose_name='Book Source'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='book_toc_source',
            field=models.FileField(blank=True, default='', help_text='This field is used to store the source of the book TOC', upload_to='books/', verbose_name='Book TOC Source'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='buy_link',
            field=models.CharField(blank=True, default='', help_text='This field is used to inform the buy link of the book', max_length=255, verbose_name='Buy link'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='columns_order',
            field=models.CharField(blank=True, default='', help_text='This field is used to inform the order of columns in the book', max_length=10, verbose_name='Columns order'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='css_class',
            field=models.CharField(blank=True, choices=[('', 'None'), ('simple', 'Simple'), ('simple-3-4', 'Simple 3 4'), ('special', 'Special'), ('special-1', 'Special 1'), ('sefer-extra', 'Sefer Extra')], default='', help_text='This field is used to inform the class to add to the book', max_length=100, verbose_name='CSS class'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='remove_class',
            field=models.CharField(blank=True, choices=[('', 'None'), ('MsoTableGrid', 'MsoTableGrid')], default='', help_text='This field is used to inform the class to remove from the book', max_length=100, verbose_name='Remove class'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='remove_tags',
            field=models.CharField(blank=True, default='', help_text='This field is used to inform the tags to remove from the book', max_length=100, verbose_name='Remove tags'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='toc_columns',
            field=models.CharField(blank=True, default='', help_text='This field is used to inform the order                                        of columns in the table of contents', max_length=10, verbose_name='TOC Columns'),
        ),
    ]
