# Generated by Django 4.0.4 on 2022-06-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0030_alter_songs_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=30, verbose_name='Method Name')),
                ('pre_process', models.BooleanField(default=False, verbose_name='Pre-process')),
                ('pro_process', models.BooleanField(default=False, verbose_name='Pro-process')),
            ],
            options={
                'verbose_name_plural': 'Method',
                'ordering': ('method_name',),
            },
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='toc_columns',
            field=models.CharField(blank=True, default='', help_text='This field is used to inform the order of columns in the table of contents', max_length=10, verbose_name='TOC Columns'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='method',
            field=models.ManyToManyField(blank=True, help_text='This field is used to inform the pre/pro process methods to apply on book', to='karaites.method', verbose_name='Methods'),
        ),
    ]
