# Generated by Django 4.0.4 on 2022-06-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0035_karaitesbookdetails_skip_process_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karaitesbookdetails',
            old_name='processed_book_intro_source',
            new_name='processed_book_source_intro',
        ),
    ]
