# Generated by Django 4.0.4 on 2022-06-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0036_rename_processed_book_intro_source_karaitesbookdetails_processed_book_source_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karaitesbookdetails',
            old_name='book_intro_source',
            new_name='book_source_intro',
        ),
    ]
