# Generated by Django 4.0.4 on 2022-06-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0038_alter_karaitesbookdetails_processed_book_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_name', models.CharField(help_text='Classification Name', max_length=30, unique=True, verbose_name='Classification Name')),
            ],
            options={
                'verbose_name_plural': 'Classification',
                'ordering': ('classification_name',),
            },
        ),
        migrations.CreateModel(
            name='FirstLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_level', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'First Level',
                'ordering': ['first_level'],
            },
        ),
        migrations.CreateModel(
            name='SecondLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_level', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Second Level',
                'ordering': ['second_level'],
            },
        ),
    ]
