# Generated by Django 4.0.4 on 2022-06-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0040_alter_karaitesbookdetails_book_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_classification',
            field=models.CharField(choices=[('00', 'Unknown'), ('10', 'Havdala Songs'), ('15', 'Passover Songs'), ('18', 'Purim Songs'), ('20', 'Prayers'), ('30', 'Shabbat Songs'), ('40', 'Supplemental Readings for specific Torah portions'), ('45', 'Tammuz/Av/Echa'), ('50', 'Wedding Songs'), ('55', 'Poetry'), ('60', 'Polemic'), ('65', 'Exhortatory'), ('70', 'Test'), ('80', 'Comments'), ('90', 'Other')], max_length=2, verbose_name='Classification'),
        ),
    ]
