# Generated by Django 4.0.4 on 2022-06-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0041_alter_karaitesbookdetails_book_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.classification', verbose_name='Classification'),
        ),
    ]
