# Generated by Django 4.0.4 on 2022-06-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0042_alter_karaitesbookdetails_book_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='classification_name',
            field=models.CharField(help_text='Classification Name', max_length=50, unique=True, verbose_name='Classification Name'),
        ),
    ]
