# Generated by Django 4.0.4 on 2022-06-15 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0043_alter_classification_classification_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='first_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.firstlevel', verbose_name='Law'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='second_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.secondlevel', verbose_name='Second level'),
        ),
    ]
