# Generated by Django 4.0.4 on 2022-06-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0044_alter_organization_first_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstlevel',
            options={'ordering': ['order', 'first_level'], 'verbose_name': '     First Level', 'verbose_name_plural': '     First Level'},
        ),
        migrations.AlterModelOptions(
            name='secondlevel',
            options={'ordering': ('order', 'second_level'), 'verbose_name': '      Second Level', 'verbose_name_plural': '     Second Level'},
        ),
        migrations.AddField(
            model_name='firstlevel',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='secondlevel',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='skip_process',
            field=models.BooleanField(default=False, help_text='This field is used to inform that this book should not be processed', verbose_name='Skip process'),
        ),
    ]
