# Generated by Django 4.0.4 on 2022-06-17 20:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0047_remove_references_foot_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='references',
            name='foot_notes_en',
        ),
        migrations.RemoveField(
            model_name='references',
            name='paragraph_text_en',
        ),
        migrations.RemoveField(
            model_name='references',
            name='paragraph_text_he',
        ),
        migrations.AddField(
            model_name='references',
            name='paragraph_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=list, help_text='Paragraph text Hebrew/English', size=None, verbose_name='Paragraph text Hebrew/English'),
        ),
        migrations.AlterField(
            model_name='references',
            name='foot_notes_he',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Foot notes Hebrew/English', null=True, size=None, verbose_name='Foot notes Hebrew/English'),
        ),
    ]
