# Generated by Django 4.0.4 on 2022-06-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0050_alter_bookasarray_book_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='classification_name_he',
            field=models.CharField(blank=True, default='', help_text='Classification Name Hebrew', max_length=50, verbose_name='Classification Name Hebrew'),
        ),
        migrations.AddField(
            model_name='firstlevel',
            name='first_level_he',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='secondlevel',
            name='second_level_he',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='references',
            name='error',
            field=models.CharField(choices=[('--', '--'), ('00', 'Verse number to big.'), ('01', 'Chapter number to big.'), ('02', 'Bible book does not exist!'), ('03', 'Invalid int for verse.'), ('04', 'Missing Chapter or verse.')], default='', max_length=2, verbose_name='error'),
        ),
    ]
