# Generated by Django 4.0.4 on 2022-07-01 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0052_remove_commenttmp_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('karaites.karaitesbookdetails',),
        ),
    ]
