# Generated by Django 4.0.4 on 2022-07-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0053_detailsproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailsproxy',
            options={'verbose_name_plural': 'Karaites book details no Html'},
        ),
    ]
