# Generated by Django 4.0.4 on 2022-10-31 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0060_alter_karaitesbookdetails_cron_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='css_class',
            field=models.CharField(blank=True, choices=[('', 'None'), ('simple', 'Simple'), ('simple-3-4', 'Simple 3 4'), ('invert-odd', 'Invert Odd'), ('special', 'Special'), ('special-1', 'Special 1'), ('sefer-extra', 'Sefer Extra')], default='', help_text='This field is used to inform the class to add to the book', max_length=100, verbose_name='CSS class'),
        ),
        migrations.CreateModel(
            name='BookAsArrayAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(default=0)),
                ('verse', models.IntegerField(default=0)),
                ('start', models.CharField(default='00:00:00.000', max_length=12)),
                ('end', models.CharField(default='00:00:00.000', max_length=12)),
                ('char_per_second', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.bookasarray', verbose_name='Book')),
            ],
            options={
                'verbose_name_plural': 'Biblical books  audio',
                'ordering': ('book', 'chapter', 'verse', 'start'),
            },
        ),
    ]
