# Generated by Django 4.0.4 on 2022-10-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0061_alter_karaitesbookdetails_css_class_bookasarrayaudio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': " Author's"},
        ),
        migrations.AlterModelOptions(
            name='bookasarray',
            options={'ordering': ('book', 'chapter'), 'verbose_name_plural': ' Biblical books'},
        ),
        migrations.AlterModelOptions(
            name='bookasarrayaudio',
            options={'ordering': ('book', 'chapter', 'verse', 'start'), 'verbose_name_plural': 'Biblical books audio'},
        ),
        migrations.AlterField(
            model_name='bookasarrayaudio',
            name='char_per_second',
            field=models.FloatField(default=0, verbose_name='Characters per second'),
        ),
    ]
