# Generated by Django 4.0.4 on 2022-10-31 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0062_alter_author_options_alter_bookasarray_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookasarrayaudio',
            options={'ordering': ('book', 'verse', 'start'), 'verbose_name_plural': 'Biblical books audio'},
        ),
        migrations.RemoveField(
            model_name='bookasarrayaudio',
            name='chapter',
        ),
    ]
