# Generated by Django 4.0.4 on 2022-10-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0063_alter_bookasarrayaudio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookasarrayaudio',
            name='end_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookasarrayaudio',
            name='start_ms',
            field=models.IntegerField(default=0),
        ),
    ]
