# Generated by Django 4.0.4 on 2022-11-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0065_bookasarray_end_ms_bookasarray_start_ms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookasarray',
            name='end_ms',
        ),
        migrations.RemoveField(
            model_name='bookasarray',
            name='start_ms',
        ),
        migrations.AddField(
            model_name='bookasarrayaudio',
            name='character',
            field=models.IntegerField(default=0),
        ),
    ]
