# Generated by Django 4.0.4 on 2022-11-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0071_alter_parsha_fifth_reading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_name', models.CharField(help_text='Audio name', max_length=100, verbose_name='Audiobook name')),
                ('audio_file', models.FileField(help_text='Audiobook file', upload_to='audiobooks/', verbose_name='Audiobook file')),
            ],
            options={
                'verbose_name_plural': 'Audiobooks',
                'ordering': ('audio_name',),
            },
        ),
    ]
