# Generated by Django 4.0.4 on 2022-11-14 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0072_audiobook'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookasarrayaudio',
            name='audio',
            field=models.ForeignKey(blank=True, help_text='Audio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.audiobook', verbose_name='Audio'),
        ),
    ]
