# Generated by Django 4.1 on 2023-04-04 19:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0075_alter_bookasarrayaudio_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiturgyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(help_text='Occasion', max_length=100, verbose_name='Occasion')),
                ('hebrew_name', models.CharField(help_text='Hebrew Name', max_length=100, verbose_name='Hebrew Name')),
                ('english_name', models.CharField(help_text='English Name', max_length=100, verbose_name='English Name')),
                ('order', models.IntegerField(default=0, help_text='Order', verbose_name='Order')),
                ('intro', models.TextField(blank=True, help_text='Intro', verbose_name='Intro')),
            ],
            options={
                'verbose_name_plural': 'Liturgy',
                'ordering': ('english_name',),
            },
        ),
        migrations.AlterModelOptions(
            name='method',
            options={},
        ),
        migrations.CreateModel(
            name='LiturgyBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_text', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=list, size=None)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LiturgyBook', to='karaites.liturgydetails')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LiturgySong', to='karaites.songs')),
            ],
            options={
                'verbose_name_plural': 'Liturgy Books',
                'ordering': ('book__english_name',),
                'unique_together': {('book', 'song')},
            },
        ),
    ]
