# Generated by Django 4.1 on 2023-04-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0078_alter_liturgybook_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liturgydetails',
            name='occasion',
            field=models.CharField(blank=True, help_text='Occasion', max_length=100, null=True, verbose_name='Occasion'),
        ),
    ]
