# Generated by Django 4.1 on 2023-05-23 17:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0080_alter_liturgybook_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='liturgydetails',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaites.author', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='liturgydetails',
            name='book_language',
            field=models.CharField(choices=[('en', 'English'), ('he', 'Hebrew'), ('he-en', 'Hebrew-English'), ('ja', 'Judeo-Arabic')], default='he', max_length=8, verbose_name='Book language'),
        ),
        migrations.AddField(
            model_name='liturgydetails',
            name='toc',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='liturgydetails',
            name='intro',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=list, size=None),
        ),
    ]
