# Generated by Django 4.1 on 2023-06-05 20:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0082_karaitesbookasarray_line_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaraitesBetterBooksProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Karaites better books',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('karaites.karaitesbookasarray',),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='occasion',
            field=models.CharField(blank=True, help_text='Occasion', max_length=100, null=True, verbose_name='Occasion'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='order',
            field=models.IntegerField(default=0, help_text='Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='karaitesbookasarray',
            name='book_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), blank=True, default=list, null=True, size=None),
        ),
    ]
