# Generated by Django 4.1 on 2023-06-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0083_karaitesbetterbooksproxy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karaitesbetterbooksproxy',
            options={'ordering': ('book', 'line_number'), 'verbose_name_plural': 'Karaites better books'},
        ),
    ]
