# Generated by Django 4.1 on 2023-08-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0085_alter_karaitesbookdetails_better_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liturgydetails',
            name='author',
        ),
        migrations.AlterField(
            model_name='booksfootnotes',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('he', 'Hebrew'), ('he-en', 'Hebrew-English'), ('ja', 'Judeo-Arabic'), ('he-en-ar', 'Hebrew-English-Arabic')], max_length=8, verbose_name='Book language'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_language',
            field=models.CharField(choices=[('en', 'English'), ('he', 'Hebrew'), ('he-en', 'Hebrew-English'), ('ja', 'Judeo-Arabic'), ('he-en-ar', 'Hebrew-English-Arabic')], max_length=8, verbose_name='Book language'),
        ),
        migrations.DeleteModel(
            name='LiturgyBook',
        ),
        migrations.DeleteModel(
            name='LiturgyDetails',
        ),
    ]
