# Generated by Django 4.1 on 2025-02-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0087_classification_order_alter_audiobook_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(default='', max_length=50, verbose_name='Menu Item')),
                ('complement', models.CharField(default='', max_length=50, verbose_name='Complement')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
        ),
        migrations.AlterModelOptions(
            name='classification',
            options={'ordering': ('order', 'classification_name'), 'verbose_name_plural': 'Classification'},
        ),
        migrations.CreateModel(
            name='Kedushot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title_left', models.CharField(default='', max_length=50, verbose_name='Menu Title Left')),
                ('menu_title_right', models.CharField(default='', max_length=50, verbose_name='Menu Title Right')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('kedushot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kedushot_single', to='karaites.menuitems', verbose_name='Kedushot')),
                ('menu_items', models.ManyToManyField(related_name='kedushot_menu_items', to='karaites.menuitems', verbose_name='Menu Items')),
            ],
            options={
                'verbose_name_plural': 'Kedushot',
                'ordering': ('order',),
            },
        ),
    ]
