# Generated by Django 4.1 on 2025-02-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0088_menuitems_alter_classification_options_kedushot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitems',
            options={'ordering': ('order',), 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.RemoveField(
            model_name='kedushot',
            name='kedushot',
        ),
    ]
