# Generated by Django 4.1 on 2025-02-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0089_alter_menuitems_options_remove_kedushot_kedushot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kedushot',
            name='menu_title_left',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Menu Title Left'),
        ),
        migrations.AlterField(
            model_name='kedushot',
            name='menu_title_right',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Menu Title Right'),
        ),
    ]
