# Generated by Django 4.1 on 2025-02-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0090_alter_kedushot_menu_title_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kedushot',
            name='belongs_to',
            field=models.CharField(blank=True, default='', editable=False, max_length=50, null=True, verbose_name='Belongs to'),
        ),
    ]
