# Generated by Django 4.1 on 2025-02-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0091_kedushot_belongs_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='pattern',
            field=models.CharField(blank=True, help_text='Pattern', max_length=50, null=True, verbose_name='Pattern'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='occasion',
            field=models.CharField(blank=True, help_text='Occasion', max_length=50, null=True, verbose_name='Occasion'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='order',
            field=models.IntegerField(default=0, help_text='Order liturgy books'),
        ),
    ]
