# Generated by Django 4.1 on 2025-02-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0092_karaitesbookdetails_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='kedushot_order',
            field=models.CharField(default='', help_text='Kedushot order', max_length=3, verbose_name='Kedushot order'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='order',
            field=models.IntegerField(default=0, help_text='Order', verbose_name='Order'),
        ),
    ]
