# Generated by Django 4.1 on 2025-02-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0094_alter_menuitems_complement_alter_menuitems_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kedushot',
            name='belongs_to',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, null=True, verbose_name='Belongs to'),
        ),
        migrations.AlterField(
            model_name='kedushot',
            name='menu_title_left',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Menu Title Left'),
        ),
        migrations.AlterField(
            model_name='kedushot',
            name='menu_title_right',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Menu Title Right'),
        ),
    ]
