# Generated by Django 4.1 on 2025-02-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0095_alter_kedushot_belongs_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='kedushot_expanded',
            field=models.BooleanField(default=False, help_text='Kedushot expanded', verbose_name='Kedushot expanded'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='kedushot_left',
            field=models.CharField(default='', help_text='Kedushot left', max_length=100, verbose_name='Kedushot left'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='kedushot_sub_title',
            field=models.CharField(default='', help_text='Kedushot sub title', max_length=100, verbose_name='Kedushot sub title'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='kedushot_title',
            field=models.CharField(default='', help_text='Kedushot title', max_length=100, verbose_name='Kedushot title'),
        ),
    ]
