# Generated by Django 4.1 on 2025-02-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0096_karaitesbookdetails_kedushot_expanded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='kedushot_left',
            field=models.CharField(blank=True, default='', help_text='Kedushot left', max_length=100, null=True, verbose_name='Kedushot left'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='kedushot_order',
            field=models.CharField(blank=True, default='', help_text='Kedushot order', max_length=3, null=True, verbose_name='Kedushot order'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='kedushot_sub_title',
            field=models.CharField(blank=True, default='', help_text='Kedushot sub title', max_length=100, null=True, verbose_name='Kedushot sub title'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='kedushot_title',
            field=models.CharField(blank=True, default='', help_text='Kedushot title', max_length=100, null=True, verbose_name='Kedushot title'),
        ),
    ]
