# Generated by Django 4.1 on 2025-02-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0097_alter_karaitesbookdetails_kedushot_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='kedushot_main_title',
            field=models.CharField(blank=True, default='', help_text='Kedushot left', max_length=100, null=True, verbose_name='Kedushot left'),
        ),
    ]
