FROM node:16.11

WORKDIR /app

# Install yarn globally
# RUN npm install -g yarn

# Copy package.json and yarn.lock first to leverage Docker cache
COPY package.json yarn.lock ./

# Install dependencies using yarn
RUN yarn install

# Copy the rest of the application code
COPY . .

EXPOSE 3000

# Use yarn start instead of npm start
CMD ["yarn", "start"]