# Build stage only
FROM node:20-alpine as build

WORKDIR /app
COPY frontend/package*.json ./
RUN yarn install
COPY frontend/ .
RUN yarn build

# Use Node.js with Express to serve static files
FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/build ./build
COPY server.js ./
RUN yarn add express

EXPOSE 3000

CMD ["node", "server.js"]
