# Build stage only
FROM node:20-alpine as build

WORKDIR /app
COPY frontend/package*.json ./
RUN yarn install
COPY frontend/ .
RUN yarn build

# Use a lightweight server to serve static files
FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/build ./build
RUN yarn global add serve
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]

