services:
  backend:
    build: .
    restart: unless-stopped
    volumes:
      - ./static:/app/static-django
    environment:
      DJANGO_CSRF_TRUSTED_ORIGINS: 'http://localhost:8000'

  frontend-proxy:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static-django:ro
    depends_on:
      - frontend
