services:
  postgres:
    image: postgres:17
    container_name: postgres
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

    restart: always
    env_file:
      - .env
    volumes:
      - ./var-17:/var/lib/postgresql/data/pgdata
      - ./docker-config/postgresql/pg_hba.conf:/var/lib/postgresql/data/pgdata/pg_hba.conf
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"
    expose:
      - 5432


  backend:
    build:
      context: .
      dockerfile: dockerfile-backend.yml
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    command: >
      bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn newkaraites.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - ./backend-static:/app/backend-static
      - ./media:/app/media
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - CONDA_DEFAULT_ENV=${CONDA_DEFAULT_ENV}
    depends_on:
      - postgres

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker-config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend-static:/app/backend-static:ro
      - ./media:/app/media:ro
      - ./frontend/build/:/app/build:ro
    env_file:
      - .env
    depends_on:
      - postgres
      - backend
    restart: always


volumes:
  vhost:
  html:

networks:
  default:
    name: nginx1_network


