services:
  backend:
    build: .
    command: gunicorn newkaraites.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - ./static:/app/static-django
      - ./media:/app/media
    expose:
      - 8000
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_HOST=db
    ports:
      - "5432:5432"

  nginx-proxy:
    depends_on:
      - backend
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static-django:ro
      - ./media:/media:ro
