# Generated by Django 3.1.7 on 2021-04-06 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('history', models.TextField(null=True, verbose_name='History')),
            ],
            options={
                'verbose_name_plural': 'Comment Author',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title_en', models.CharField(max_length=100, null=True, verbose_name='Book title English')),
                ('book_title_he', models.CharField(max_length=100, null=True, verbose_name='Book title Hebrew')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='Presentation order')),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True, verbose_name='A comment')),
                ('comment_language', models.CharField(choices=[('En', ' English'), ('He', 'Hebrew')], max_length=2, verbose_name='Comment language')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.commentauthor', verbose_name='Who comment')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='BookText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_en', models.IntegerField(default=0, verbose_name='Chapter')),
                ('verse_en', models.IntegerField(default=0, verbose_name='Verse')),
                ('chapter_he', models.IntegerField(default=0, verbose_name='Chapter')),
                ('verse_he', models.IntegerField(default=0, verbose_name='Verse')),
                ('text_en', models.TextField(null=True, verbose_name='English chapter Verse text')),
                ('text_he', models.TextField(null=True, verbose_name='Hebrew chapter Verse text')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaites.organization', verbose_name='Book')),
                ('comments', models.ManyToManyField(to='karaites.Comment')),
            ],
            options={
                'verbose_name_plural': 'Book text',
            },
        ),
    ]
