# Generated by Django 3.1.7 on 2021-04-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktext',
            old_name='chapter_en',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='booktext',
            old_name='verse_en',
            new_name='verse',
        ),
        migrations.AlterUniqueTogether(
            name='booktext',
            unique_together={('book', 'chapter', 'verse')},
        ),
        migrations.RemoveField(
            model_name='booktext',
            name='chapter_he',
        ),
        migrations.RemoveField(
            model_name='booktext',
            name='verse_he',
        ),
    ]
