# Generated by Django 3.1.7 on 2021-04-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0002_auto_20210407_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktext',
            options={'ordering': ('book', 'chapter', 'verse'), 'verbose_name_plural': 'Book text'},
        ),
    ]
