# Generated by Django 3.1.7 on 2021-04-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0003_auto_20210407_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentauthor',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='History'),
        ),
    ]
