# Generated by Django 3.1.7 on 2021-04-08 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0004_auto_20210407_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('book', 'chapter', 'verse'), 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='booktext',
            name='comments',
        ),
        migrations.AddField(
            model_name='booktext',
            name='comments_count',
            field=models.IntegerField(default=0, verbose_name='Total Comments'),
        ),
        migrations.AddField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.organization', verbose_name='Book'),
        ),
        migrations.AddField(
            model_name='comment',
            name='chapter',
            field=models.IntegerField(default=0, verbose_name='Chapter'),
        ),
        migrations.AddField(
            model_name='comment',
            name='verse',
            field=models.IntegerField(default=0, verbose_name='Verse'),
        ),
    ]
