# Generated by Django 3.1.7 on 2021-04-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0005_auto_20210408_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktext',
            name='comments_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total Comments'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='chapter',
            field=models.IntegerField(default=1, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='verse',
            field=models.IntegerField(default=1, verbose_name='Verse'),
        ),
    ]
