# Generated by Django 3.1.7 on 2021-04-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0006_auto_20210408_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh')], default=0, verbose_name='First Level'),
        ),
        migrations.AddField(
            model_name='organization',
            name='second_level',
            field=models.IntegerField(choices=[(1, 'Torah'), (2, 'Prophets'), (3, 'Writings')], default=0, verbose_name='Second level'),
        ),
    ]
