# Generated by Django 3.2 on 2022-04-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0006_auto_20220425_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='buy_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='song',
            field=models.BooleanField(default=False),
        ),
    ]
