# Generated by Django 3.1.7 on 2021-04-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0007_auto_20210408_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='chapters',
            field=models.IntegerField(default=0, verbose_name='Number of Chapters'),
        ),
    ]
