# Generated by Django 3.2 on 2021-04-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0008_organization_chapters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['order'], 'verbose_name_plural': '  Organizations'},
        ),
        migrations.AddField(
            model_name='comment',
            name='comments_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Comment count'),
        ),
    ]
