# Generated by Django 3.2 on 2022-05-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0008_karaitesbookdetails_index_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltextsearch',
            name='path',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='fulltextsearchhebrew',
            name='path',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_classification',
            field=models.CharField(choices=[('00', 'Unknown'), ('10', 'Havdala Songs'), ('15', 'Passover Songs'), ('18', 'Purim Songs'), ('20', 'Prayers'), ('30', 'Shabbat Songs'), ('40', 'Supplemental Readings for specific Torah portions'), ('50', 'Wedding Songs'), ('55', 'Poetry'), ('60', 'Polemic'), ('65', 'Exhortatory'), ('70', 'Test'), ('80', 'Comments'), ('90', 'Other')], max_length=2, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh'), (2, 'Talmud'), (3, 'Halakhah'), (4, 'Liturgy'), (5, 'Polemics'), (6, 'Songs'), (7, 'Prayers'), (8, 'Comments'), (9, 'Poetry (Non-Liturgical)'), (10, 'Other'), (11, 'Exhortatory')], default=0, verbose_name='Law'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh'), (2, 'Talmud'), (3, 'Halakhah'), (4, 'Liturgy'), (5, 'Polemics'), (6, 'Songs'), (7, 'Prayers'), (8, 'Comments'), (9, 'Poetry (Non-Liturgical)'), (10, 'Other'), (11, 'Exhortatory')], default=0, verbose_name='Law'),
        ),
    ]
