# Generated by Django 3.2 on 2021-04-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0010_alter_comment_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_language',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_en',
            field=models.TextField(null=True, verbose_name='Comment English'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_he',
            field=models.TextField(null=True, verbose_name='Comment Hebrew'),
        ),
    ]
