# Generated by Django 4.0 on 2022-05-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0011_englishword'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishword',
            name='word_count',
            field=models.IntegerField(default=0, verbose_name='Word Count in all documents'),
        ),
    ]
