# Generated by Django 3.2 on 2021-04-13 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0011_auto_20210412_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.commentauthor', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_he',
            field=models.TextField(blank=True, null=True, verbose_name='Comment Hebrew'),
        ),
    ]
