# Generated by Django 3.2 on 2021-04-15 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0012_auto_20210413_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='chapters',
        ),
        migrations.CreateModel(
            name='ChapterVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(default=0, verbose_name='Chapter')),
                ('verses', models.IntegerField(default=0, verbose_name='Total verses on this chapter.')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.organization', verbose_name='Book')),
            ],
            options={
                'verbose_name_plural': 'Verses by Chapter and Book',
            },
        ),
    ]
