# Generated by Django 4.0 on 2022-05-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0012_englishword_word_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisspelledWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misspelled_word', models.CharField(db_index=True, max_length=40, verbose_name='Misspelled word')),
                ('corrected_word', models.CharField(db_index=True, max_length=40, verbose_name='Corrected word')),
            ],
            options={
                'verbose_name_plural': 'Misspelled words',
                'ordering': ('misspelled_word',),
            },
        ),
        migrations.AlterModelOptions(
            name='englishword',
            options={'ordering': ('word',), 'verbose_name_plural': 'English words'},
        ),
        migrations.AlterField(
            model_name='englishword',
            name='word_count',
            field=models.IntegerField(default=1, verbose_name='Word Count in all documents'),
        ),
    ]
