# Generated by Django 3.2 on 2021-04-16 20:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0013_auto_20210415_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktext',
            options={'ordering': ('book', 'chapter', 'verse'), 'verbose_name_plural': '  Book text'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['order'], 'verbose_name_plural': '   Organizations'},
        ),
        migrations.AddField(
            model_name='organization',
            name='chapters',
            field=models.IntegerField(default=1, verbose_name='How many chapters in a book'),
        ),
        migrations.AddField(
            model_name='organization',
            name='verses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, editable=False, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='ChapterVerse',
        ),
    ]
