# Generated by Django 4.0 on 2022-05-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0014_remove_misspelledword_corrected_word_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misspelledword',
            name='correct_word',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Correct word'),
        ),
    ]
