# Generated by Django 3.2 on 2021-04-17 13:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0014_auto_20210416_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='chapters',
            field=models.IntegerField(default=1, verbose_name='How many chapters in this book'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='verses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, editable=False, null=True, size=None, verbose_name='How many verses in each chapter'),
        ),
    ]
