# Generated by Django 3.2 on 2021-04-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0015_auto_20210417_1348'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booktext',
            unique_together=set(),
        ),
    ]
