# Generated by Django 4.0.4 on 2022-05-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0015_alter_misspelledword_correct_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksFootNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footnote_ref', models.CharField(default='', max_length=6, verbose_name='Footnote number')),
                ('footnotes', models.TextField(default='', verbose_name='Footnotes')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaites.karaitesbookdetails', verbose_name='Book')),
            ],
            options={
                'verbose_name_plural': 'Books footnotes',
                'ordering': ('book', 'footnote_ref'),
            },
        ),
    ]
