# Generated by Django 3.2 on 2021-04-19 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0016_alter_booktext_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh')], default=0, verbose_name='Law'),
        ),
        migrations.CreateModel(
            name='BookAsJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_json', models.JSONField(verbose_name='Book as Json')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaites.booktext', verbose_name='Book')),
            ],
            options={
                'verbose_name_plural': 'Books as Json',
            },
        ),
    ]
