# Generated by Django 3.2 on 2021-04-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0017_auto_20210419_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookasjson',
            name='book_json',
        ),
        migrations.AddField(
            model_name='bookasjson',
            name='book_json_en',
            field=models.JSONField(blank=True, null=True, verbose_name='Book as Json English'),
        ),
        migrations.AddField(
            model_name='bookasjson',
            name='book_json_he',
            field=models.JSONField(blank=True, null=True, verbose_name='Book as Json Hebrew'),
        ),
    ]
