# Generated by Django 4.0.4 on 2022-05-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0017_rename_footnotes_booksfootnotes_footnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksfootnotes',
            name='language',
            field=models.CharField(default='en', max_length=2, verbose_name='Language'),
        ),
    ]
