# Generated by Django 4.0.4 on 2022-05-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0018_booksfootnotes_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksfootnotes',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('he', 'Hebrew'), ('en,he', 'Hebrew/English'), ('ja', 'Judeo-Arabic')], max_length=8, verbose_name='Book language'),
        ),
    ]
