# Generated by Django 4.0.4 on 2022-05-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0019_alter_booksfootnotes_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksfootnotes',
            name='footnote_ref',
            field=models.CharField(default='', max_length=20, verbose_name='Footnote ref.'),
        ),
    ]
