# Generated by Django 3.2 on 2021-04-20 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0019_rename_bookasjson_bookjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookjson',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaites.organization', verbose_name='Book'),
        ),
    ]
