# Generated by Django 3.2 on 2021-04-27 15:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0020_alter_bookjson_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Comment English'),
        ),
    ]
