# Generated by Django 4.0.4 on 2022-05-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0020_alter_booksfootnotes_footnote_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksfootnotes',
            options={'ordering': ('book', 'footnote_number'), 'verbose_name_plural': 'Books footnotes'},
        ),
        migrations.AddField(
            model_name='booksfootnotes',
            name='footnote_number',
            field=models.IntegerField(default=0, verbose_name='Footnote number'),
        ),
    ]
