# Generated by Django 3.2 on 2021-04-27 17:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0021_alter_comment_comment_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Comment English'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_he',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Comment Hebrew'),
        ),
    ]
