# Generated by Django 3.2 on 2021-04-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0022_auto_20210427_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Presentation order'),
        ),
    ]
