# Generated by Django 3.2 on 2021-04-27 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0023_comment_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('book', 'chapter', 'verse', 'order'), 'verbose_name_plural': 'Comments'},
        ),
    ]
