# Generated by Django 4.0.4 on 2022-06-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0024_bookclassificationfirst_bookclassificationsecond_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookclassificationfirst',
            options={'ordering': ('order',), 'verbose_name_plural': 'Book Classification First'},
        ),
        migrations.AlterModelOptions(
            name='bookclassificationsecond',
            options={'ordering': ('order',), 'verbose_name_plural': 'Book Classification Second'},
        ),
        migrations.AddField(
            model_name='bookclassificationfirst',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='bookclassificationsecond',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
