# Generated by Django 3.2 on 2021-04-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0024_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('book', 'chapter', 'verse'), 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='order',
        ),
    ]
