# Generated by Django 3.2 on 2021-05-10 15:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0025_auto_20210428_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktext',
            options={'ordering': ('book', 'chapter', 'verse'), 'verbose_name_plural': '  Biblical Text'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('book', 'chapter', 'verse'), 'verbose_name_plural': 'Commentaries'},
        ),
        migrations.AlterModelOptions(
            name='commentauthor',
            options={'verbose_name_plural': 'Commentary Author'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['order'], 'verbose_name_plural': '   Architecture'},
        ),
        migrations.CreateModel(
            name='BookAsArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_text', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=4), size=None)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaites.organization', verbose_name='Book')),
            ],
        ),
    ]
