# Generated by Django 3.2 on 2021-05-10 17:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0026_auto_20210510_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookasarray',
            name='chapter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookasarray',
            name='book_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=3), size=None),
        ),
    ]
