# Generated by Django 3.2 on 2021-05-10 17:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0027_auto_20210510_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookasarray',
            name='book_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=2), size=None),
        ),
    ]
