# Generated by Django 4.0.4 on 2022-06-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0028_karaitesbookdetails_book_intro_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karaitesbookdetails',
            name='book_source',
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='book_source_en',
            field=models.FileField(default='', help_text='This field is used to store the English source of the book', upload_to='books/', verbose_name='Book Source English'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='book_source_he',
            field=models.FileField(default='', help_text='This field is used to store the Hebrew source of the book', upload_to='books/', verbose_name='Book Source Hebrew'),
        ),
    ]
