# Generated by Django 3.2 on 2021-05-10 17:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0028_alter_bookasarray_book_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookasarray',
            name='book_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=3), size=None),
        ),
    ]
