# Generated by Django 3.2 on 2021-05-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0029_alter_bookasarray_book_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments_count',
        ),
        migrations.AddField(
            model_name='commentauthor',
            name='comments_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Comment count'),
        ),
        migrations.DeleteModel(
            name='BookJson',
        ),
    ]
