# Generated by Django 4.0.4 on 2022-06-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0029_remove_karaitesbookdetails_book_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ('song_title',), 'verbose_name_plural': 'Songs'},
        ),
    ]
