# Generated by Django 3.2 on 2021-05-11 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0030_auto_20210511_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookasarray',
            options={'ordering': ('book', 'chapter')},
        ),
    ]
