# Generated by Django 4.0.4 on 2022-06-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0031_method_alter_karaitesbookdetails_toc_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='processed_book_source',
            field=models.FileField(blank=True, default='', help_text='This field is used to store the processed book source', upload_to='processed/', verbose_name='Processed Book Source'),
        ),
    ]
