# Generated by Django 3.2 on 2021-05-17 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0031_alter_bookasarray_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentAuthor',
            new_name='Author',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': "Author's"},
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaites.organization', verbose_name='Comments on Book'),
        ),
    ]
