# Generated by Django 3.2 on 2021-05-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0032_auto_20210517_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title_en', models.CharField(max_length=100, null=True, verbose_name='Book title English')),
                ('book_title_he', models.CharField(max_length=100, null=True, verbose_name='Book title Hebrew')),
                ('classification', models.SmallIntegerField(choices=[(1, 'Comment'), (100, 'Other')], verbose_name='Book classification')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaites.author', verbose_name='Author')),
            ],
            options={
                'verbose_name_plural': 'Other books',
            },
        ),
    ]
