# Generated by Django 4.0.4 on 2022-06-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0032_karaitesbookdetails_processed_book_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karaitesbookdetails',
            name='processed_book_source',
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='processed_book_intro_source',
            field=models.FileField(blank=True, default='', help_text='This field is used to store the processed source of the book introduction', upload_to='processed/', verbose_name='Book proccessed Intro Source'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='processed_book_source_en',
            field=models.FileField(default='', help_text='This field is used to store the processed English source of the book', upload_to='processed/', verbose_name='Book processed Source English'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='processed_book_source_he',
            field=models.FileField(default='', help_text='This field is used to store the processed Hebrew source of the book', upload_to='processed/', verbose_name='Book processed Source Hebrew'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='processed_book_toc_source',
            field=models.FileField(blank=True, default='', help_text='This field is used to store the source of the processed book TOC', upload_to='processed/', verbose_name='Book processed TOC Source'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_toc_source',
            field=models.FileField(blank=True, default='', help_text='This field is used to store the processed source of the book TOC', upload_to='processed/', verbose_name='Book processed TOC  Source'),
        ),
    ]
