# Generated by Django 3.2 on 2021-05-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0033_otherbooks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['order'], 'verbose_name_plural': '    Architecture'},
        ),
        migrations.AlterModelOptions(
            name='otherbooks',
            options={'verbose_name_plural': '  Other books'},
        ),
        migrations.AddField(
            model_name='comment',
            name='source_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaites.otherbooks', verbose_name='Source book'),
        ),
        migrations.AlterField(
            model_name='otherbooks',
            name='book_title_he',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Book title Hebrew'),
        ),
        migrations.AlterField(
            model_name='otherbooks',
            name='classification',
            field=models.SmallIntegerField(choices=[(1, 'Commentaries'), (100, 'Other')], verbose_name='Book classification'),
        ),
    ]
