# Generated by Django 4.0.4 on 2022-06-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0033_remove_karaitesbookdetails_processed_book_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karaitesbookdetails',
            old_name='book_source_en',
            new_name='book_source',
        ),
        migrations.RenameField(
            model_name='karaitesbookdetails',
            old_name='processed_book_source_en',
            new_name='processed_book_source',
        ),
        migrations.RemoveField(
            model_name='karaitesbookdetails',
            name='book_source_he',
        ),
        migrations.RemoveField(
            model_name='karaitesbookdetails',
            name='processed_book_source_he',
        ),
    ]
