# Generated by Django 3.2 on 2021-05-17 17:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0034_auto_20210517_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='foot_notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None),
        ),
    ]
