# Generated by Django 4.0.4 on 2022-06-14 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('karaites', '0034_rename_book_source_en_karaitesbookdetails_book_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='skip_process',
            field=models.BooleanField(default=False, help_text='This field is used to inform that book should not be processed', verbose_name='Skip process'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='user',
            field=models.ForeignKey(blank=True, default=None, help_text='This field is used to inform the user who added the book', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_intro_source',
            field=models.FileField(blank=True, default='', help_text='This field is used to store the source of the book introduction', upload_to='intro/', verbose_name='Book Intro Source'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_source',
            field=models.FileField(default='', help_text='This field is used to store the source of the book', upload_to='books/', verbose_name='Book Source '),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_toc_source',
            field=models.FileField(blank=True, default='', help_text='This field is used to store the processed source of the book TOC', upload_to='toc/', verbose_name='Book TOC  Source'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='columns_order',
            field=models.CharField(blank=True, default='0,1', help_text='This field is used to inform the order of columns in the book', max_length=10, verbose_name='Columns order'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='processed_book_intro_source',
            field=models.FileField(blank=True, default='', help_text='This field is used to store the processed source of the book introduction', upload_to='processed_intro/', verbose_name='Book processed Intro Source'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='processed_book_source',
            field=models.FileField(default='', help_text='This field is used to store the processed  source of the book', upload_to='processed_source/', verbose_name='Book processed Source'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='processed_book_toc_source',
            field=models.FileField(blank=True, default='', help_text='This field is used to store the source of the processed book TOC', upload_to='processed_toc/', verbose_name='Book processed TOC Source'),
        ),
    ]
