# Generated by Django 3.2 on 2021-05-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0035_comment_foot_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('book', 'chapter', 'verse', 'comment_number'), 'verbose_name_plural': 'Commentaries'},
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_number',
            field=models.SmallIntegerField(default=0, verbose_name='Comment Number'),
        ),
    ]
