# Generated by Django 3.2 on 2021-05-31 19:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0036_auto_20210517_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='foot_notes',
            new_name='foot_notes_en',
        ),
        migrations.RemoveField(
            model_name='author',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='booktext',
            name='comments_count',
        ),
        migrations.AddField(
            model_name='author',
            name='comments_count_en',
            field=models.IntegerField(default=0, editable=False, verbose_name='Comments English'),
        ),
        migrations.AddField(
            model_name='author',
            name='comments_count_he',
            field=models.IntegerField(default=0, editable=False, verbose_name='Comment Hebrew'),
        ),
        migrations.AddField(
            model_name='booktext',
            name='comments_count_en',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total Comments EN'),
        ),
        migrations.AddField(
            model_name='booktext',
            name='comments_count_he',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total Comments HE'),
        ),
        migrations.AddField(
            model_name='comment',
            name='foot_notes_he',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='bookasarray',
            name='book_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=4), size=None),
        ),
    ]
