# Generated by Django 4.0.4 on 2022-06-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0037_rename_book_intro_source_karaitesbookdetails_book_source_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='processed_book_source',
            field=models.FileField(blank=True, default='', editable=False, help_text='This field is used to store the processed  source of the book', upload_to='processed_source/', verbose_name='Book processed Source'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='processed_book_source_intro',
            field=models.FileField(blank=True, default='', editable=False, help_text='This field is used to store the processed source of the book introduction', upload_to='processed_intro/', verbose_name='Book processed Intro Source'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='processed_book_toc_source',
            field=models.FileField(blank=True, default='', editable=False, help_text='This field is used to store the source of the processed book TOC', upload_to='processed_toc/', verbose_name='Book processed TOC Source'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='songs',
            field=models.ManyToManyField(blank=True, to='karaites.songs'),
        ),
    ]
