# Generated by Django 3.2 on 2021-05-31 20:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0038_alter_bookasarray_book_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookasarray',
            name='book_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=4), size=None),
        ),
    ]
