# Generated by Django 4.0.4 on 2022-06-15 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0039_classification_firstlevel_secondlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.classification', verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='first_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.firstlevel', verbose_name='Law'),
        ),
    ]
