# Generated by Django 3.2 on 2021-06-07 17:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0042_alter_bookasarray_book_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.author', verbose_name='Author'),
        ),
        migrations.CreateModel(
            name='CommentTmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(default=1, verbose_name='Chapter')),
                ('verse', models.IntegerField(default=1, verbose_name='Verse')),
                ('comment_number', models.SmallIntegerField(default=0, verbose_name='Comment Number')),
                ('comment_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Comment English')),
                ('comment_he', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Comment Hebrew')),
                ('foot_notes_en', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None)),
                ('foot_notes_he', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaites.organization', verbose_name='Comments on Book')),
                ('comment_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.author', verbose_name='Author')),
                ('source_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaites.otherbooks', verbose_name='Source book')),
            ],
            options={
                'verbose_name_plural': 'Comments Tmp',
            },
        ),
    ]
