# Generated by Django 3.2 on 2021-06-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0043_auto_20210607_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('book', 'chapter', 'verse'), 'verbose_name_plural': 'Commentaries'},
        ),
        migrations.AlterModelOptions(
            name='commenttmp',
            options={'ordering': ('book', 'chapter', 'verse', 'comment_number'), 'verbose_name_plural': 'Comments Tmp'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_number',
        ),
    ]
