# Generated by Django 3.2 on 2021-06-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0044_auto_20210609_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('book', 'chapter', 'verse', 'pk'), 'verbose_name_plural': 'Commentaries'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_en',
            field=models.TextField(blank=True, null=True, verbose_name='Comment English'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_he',
            field=models.TextField(blank=True, null=True, verbose_name='Comment Hebrew'),
        ),
    ]
