# Generated by Django 3.2 on 2021-06-16 18:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0045_auto_20210616_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Comment English'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_he',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Comment Hebrew'),
        ),
    ]
