# Generated by Django 3.2 on 2021-06-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0046_auto_20210616_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktext',
            name='book_he',
            field=models.CharField(default='', max_length=25, verbose_name='Book He'),
        ),
        migrations.AddField(
            model_name='booktext',
            name='chapter_he',
            field=models.CharField(default='', max_length=3, verbose_name='Chapter He'),
        ),
        migrations.AddField(
            model_name='booktext',
            name='verse_he',
            field=models.CharField(default='', max_length=3, verbose_name='Verse He'),
        ),
        migrations.AlterField(
            model_name='booktext',
            name='comments_count_en',
            field=models.IntegerField(default=0, editable=False, verbose_name='EN Cmt.'),
        ),
        migrations.AlterField(
            model_name='booktext',
            name='comments_count_he',
            field=models.IntegerField(default=0, editable=False, verbose_name='HE Cmt.'),
        ),
    ]
