# Generated by Django 4.0.4 on 2022-06-17 20:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0046_delete_bookclassificationfirst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='references',
            name='foot_notes',
        ),
        migrations.RemoveField(
            model_name='references',
            name='paragraph_text',
        ),
        migrations.AddField(
            model_name='references',
            name='foot_notes_en',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Foot notes English', null=True, size=None, verbose_name='Foot notes English'),
        ),
        migrations.AddField(
            model_name='references',
            name='foot_notes_he',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Foot notes Hebrew', null=True, size=None, verbose_name='Foot notes Hebrew'),
        ),
        migrations.AddField(
            model_name='references',
            name='paragraph_text_en',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=list, help_text='Paragraph text English', size=None, verbose_name='Paragraph text English'),
        ),
        migrations.AddField(
            model_name='references',
            name='paragraph_text_he',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=list, help_text='Paragraph text Hebrew', size=None, verbose_name='Paragraph text Hebrew'),
        ),
        migrations.AlterField(
            model_name='references',
            name='bible_ref_en',
            field=models.CharField(default='', help_text='ref. English', max_length=40, verbose_name='ref. English'),
        ),
        migrations.AlterField(
            model_name='references',
            name='bible_ref_he',
            field=models.CharField(default='', help_text='ref. Hebrew', max_length=40, verbose_name='ref. Hebrew'),
        ),
        migrations.AlterField(
            model_name='references',
            name='karaites_book',
            field=models.ForeignKey(help_text='Karaites book', on_delete=django.db.models.deletion.CASCADE, to='karaites.karaitesbookdetails', verbose_name='Karaites book'),
        ),
        migrations.AlterField(
            model_name='references',
            name='paragraph_number',
            field=models.IntegerField(default=0, help_text='Karaites paragraph that references Bible book', verbose_name='Karaites paragraph that references Bible book'),
        ),
    ]
