# Generated by Django 3.2 on 2021-06-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0047_auto_20210617_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktext',
            name='chapter_he',
        ),
        migrations.RemoveField(
            model_name='booktext',
            name='verse_he',
        ),
    ]
