# Generated by Django 4.0.4 on 2022-06-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0048_remove_references_foot_notes_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='references',
            old_name='foot_notes_he',
            new_name='foot_notes',
        ),
    ]
