# Generated by Django 3.2 on 2021-06-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0048_auto_20210617_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktext',
            name='book_he',
        ),
        migrations.AlterField(
            model_name='booktext',
            name='text_en',
            field=models.TextField(null=True, verbose_name='English text'),
        ),
        migrations.AlterField(
            model_name='booktext',
            name='text_he',
            field=models.TextField(null=True, verbose_name='Hebrew text'),
        ),
    ]
