# Generated by Django 3.2 on 2021-06-25 16:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0049_auto_20210617_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaraitesBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_language', models.CharField(choices=[('En', ' English'), ('He', 'Hebrew')], max_length=2, verbose_name='Book language')),
                ('book_classification', models.CharField(choices=[('01', 'Prayer'), ('02', 'Blessing'), ('03', 'Karaite Jewish practice'), ('04', 'Egyptian Karaite Tradition'), ('05', 'Poems'), ('06', 'Recipes')], max_length=2, verbose_name='Classification')),
                ('book_title', models.CharField(max_length=100, verbose_name='Book_title')),
                ('chapter', models.IntegerField(default=1, verbose_name='Chapter')),
                ('chapter_title', models.CharField(max_length=200, verbose_name='Chapter title')),
                ('chapter_text', models.TextField(verbose_name='Chapter title')),
                ('foot_notes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None)),
            ],
            options={
                'verbose_name_plural': 'Other books',
            },
        ),
    ]
