# Generated by Django 3.2 on 2021-06-30 13:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0049_auto_20210617_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaraitesBookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_language', models.CharField(choices=[('en', ' English'), ('he', 'Hebrew')], max_length=2, verbose_name='Book language')),
                ('book_classification', models.CharField(choices=[('01', 'Prayer'), ('02', 'Blessing'), ('03', 'Karaite Jewish practice'), ('04', 'Egyptian Karaite Tradition'), ('05', 'Poems'), ('06', 'Recipes')], max_length=2, verbose_name='Classification')),
                ('book_title', models.CharField(max_length=100, verbose_name='Book_title')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karaites.author', verbose_name='Book Author')),
            ],
            options={
                'verbose_name_plural': 'Karaites book details',
            },
        ),
        migrations.CreateModel(
            name='KaraitesBookText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(default=0, verbose_name='Chapter number')),
                ('chapter_number_la', models.TextField(blank=True, null=True, verbose_name='Chapter in language')),
                ('chapter_title', models.TextField(blank=True, null=True, verbose_name='Chapter title')),
                ('chapter_text', models.TextField(verbose_name='Chapter text')),
                ('foot_notes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaites.karaitesbookdetails', verbose_name='Karaite book details')),
            ],
            options={
                'verbose_name_plural': 'Karaites book text',
            },
        ),
        migrations.DeleteModel(
            name='Ref',
        ),
    ]
