# Generated by Django 3.2 on 2021-06-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0050_auto_20210630_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbooktext',
            name='chapter_number',
            field=models.IntegerField(default=0, verbose_name='Chapter #'),
        ),
        migrations.AlterField(
            model_name='karaitesbooktext',
            name='chapter_number_la',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Chapter #'),
        ),
    ]
