# Generated by Django 3.2 on 2021-06-25 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0050_karaitesbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ref',
        ),
        migrations.AlterModelOptions(
            name='karaitesbook',
            options={'verbose_name_plural': 'Karaites books'},
        ),
        migrations.AddField(
            model_name='karaitesbook',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.author', verbose_name='Book Author'),
        ),
        migrations.AlterField(
            model_name='karaitesbook',
            name='chapter_text',
            field=models.TextField(verbose_name='Chapter text'),
        ),
    ]
