# Generated by Django 4.0.4 on 2022-07-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0051_classification_classification_name_he_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttmp',
            name='book',
        ),
        migrations.RemoveField(
            model_name='commenttmp',
            name='comment_author',
        ),
        migrations.RemoveField(
            model_name='commenttmp',
            name='source_book',
        ),
        migrations.RemoveField(
            model_name='otherbooks',
            name='author',
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_title_he',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Title Hebrew'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentTmp',
        ),
        migrations.DeleteModel(
            name='OtherBooks',
        ),
    ]
