# Generated by Django 4.0.4 on 2022-07-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0054_alter_detailsproxy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstlevel',
            name='break_on_classification',
            field=models.BooleanField(default=False, help_text='Break on classification ex.:Liturgy', verbose_name='Break on classification'),
        ),
        migrations.AlterField(
            model_name='firstlevel',
            name='first_level',
            field=models.CharField(help_text='First level in English', max_length=50, unique=True, verbose_name='First level English'),
        ),
        migrations.AlterField(
            model_name='firstlevel',
            name='first_level_he',
            field=models.CharField(blank=True, default='', help_text='First level in Hebrew', max_length=50, verbose_name='First level in Hebrew'),
        ),
        migrations.AlterField(
            model_name='firstlevel',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display order'),
        ),
    ]
