# Generated by Django 3.2 on 2021-07-22 18:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0054_alter_bookasarray_book_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookasarray',
            options={'ordering': ('book', 'chapter'), 'verbose_name_plural': 'Biblical books as array'},
        ),
        migrations.CreateModel(
            name='KaraitesBookAsArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_text', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=4), default=list, size=None)),
                ('foot_notes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaites.karaitesbookdetails', verbose_name='Karaite book details')),
            ],
            options={
                'verbose_name_plural': 'Karaites book text as array',
            },
        ),
    ]
