# Generated by Django 3.2 on 2021-07-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0055_auto_20210722_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karaitesbookasarray',
            options={'ordering': ('book', 'chapter'), 'verbose_name_plural': 'Karaites book text as array'},
        ),
        migrations.AddField(
            model_name='karaitesbookasarray',
            name='chapter',
            field=models.IntegerField(default=0),
        ),
    ]
