# Generated by Django 4.0.4 on 2022-07-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0055_firstlevel_break_on_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstlevel',
            name='url',
            field=models.CharField(default='', help_text='URL should be only one word without spaces', max_length=20, verbose_name='URL'),
        ),
    ]
