# Generated by Django 4.0.4 on 2022-07-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0056_firstlevel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Author Name in English', max_length=100, verbose_name='Author Name in English'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_he',
            field=models.CharField(blank=True, default='', help_text='Name in Hebrew if any', max_length=100, verbose_name='Author name in Hebrew'),
        ),
        migrations.AlterField(
            model_name='firstlevel',
            name='url',
            field=models.CharField(default='', help_text="URL should be only one word without spaces don't change the older ones. Keep then in English", max_length=20, verbose_name='URL'),
        ),
    ]
