# Generated by Django 3.2 on 2021-07-26 16:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0056_auto_20210722_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karaitesbookasarray',
            options={'ordering': ('book', 'page'), 'verbose_name_plural': 'Karaites book text as array'},
        ),
        migrations.RenameField(
            model_name='karaitesbookasarray',
            old_name='chapter',
            new_name='page',
        ),
        migrations.AddField(
            model_name='karaitesbookasarray',
            name='paragraph_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='karaitesbookasarray',
            name='book_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=list, size=None),
        ),
    ]
