# Generated by Django 3.2 on 2021-07-29 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0057_auto_20210726_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karaitesbookasarray',
            options={'ordering': ('book', 'page', 'paragraph_number'), 'verbose_name_plural': 'Karaites book text as array'},
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_number', models.IntegerField(default=0, verbose_name='Karaites paragraph that references Bible book')),
                ('bible_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaites.organization', verbose_name='Bible book')),
                ('karaites_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaites.karaitesbookdetails', verbose_name='Karaites book')),
            ],
            options={
                'verbose_name_plural': 'Karaite references on Bible books.',
            },
        ),
    ]
