# Generated by Django 3.2 on 2021-07-30 16:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0058_auto_20210729_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='references',
            name='paragraph_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_title',
            field=models.CharField(max_length=100, verbose_name='Karaites book title'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='book_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Bible book title English'),
        ),
    ]
