# Generated by Django 3.2 on 2021-08-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0059_auto_20210730_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', ' English'), ('he', 'Hebrew')], max_length=2, verbose_name='Language')),
                ('category', models.CharField(choices=[(1, 'Tanakh')], max_length=30, verbose_name='Category')),
                ('sub_category', models.CharField(choices=[(1, 'Torah'), (2, 'Prophets'), (3, 'Writings')], max_length=30, verbose_name='Sub-category')),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Classification Order')),
            ],
            options={
                'verbose_name_plural': 'Book Classification',
                'ordering': ('category', 'sub_category', 'language'),
            },
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh')], default=0, verbose_name='Law'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='second_level',
            field=models.IntegerField(choices=[(1, 'Torah'), (2, 'Prophets'), (3, 'Writings')], default=0, verbose_name='Second level'),
        ),
    ]
