# Generated by Django 4.0.4 on 2022-07-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0059_karaitesbookdetails_cron_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='cron_schedule',
            field=models.BooleanField(default=False, editable=False, help_text='This field is used to inform if the books is scheduled to be processed', verbose_name='Cron schedule'),
        ),
    ]
