# Generated by Django 3.2 on 2021-08-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0060_auto_20210803_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'ordering': ('category', 'sub_category', 'language'), 'verbose_name_plural': '     Book Classification'},
        ),
        migrations.AlterField(
            model_name='classification',
            name='category',
            field=models.IntegerField(choices=[(1, 'Tanakh')], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='sub_category',
            field=models.IntegerField(choices=[(1, 'Torah'), (2, 'Prophets'), (3, 'Writings')], verbose_name='Sub-category'),
        ),
    ]
