# Generated by Django 3.2 on 2021-08-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0061_auto_20210803_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('he', 'Hebrew'), ('en/he', 'English/Hebrew')], max_length=5, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_language',
            field=models.CharField(choices=[('en', 'English'), ('he', 'Hebrew'), ('en/he', 'English/Hebrew')], max_length=5, verbose_name='Book language'),
        ),
    ]
