# Generated by Django 3.2 on 2021-08-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0062_auto_20210803_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='summary_en',
            field=models.TextField(default='', verbose_name='Summary English'),
        ),
        migrations.AddField(
            model_name='organization',
            name='summary_he',
            field=models.TextField(default='', verbose_name='Summary Hebrew'),
        ),
    ]
