# Generated by Django 3.2 on 2021-08-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0063_auto_20210803_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karaitesbookdetails',
            name='second_level',
        ),
        migrations.AlterField(
            model_name='classification',
            name='category',
            field=models.IntegerField(choices=[(1, 'Tanakh'), (3, 'Halakhah')], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh'), (3, 'Halakhah')], default=0, verbose_name='Law'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh'), (3, 'Halakhah')], default=0, verbose_name='Law'),
        ),
    ]
