# Generated by Django 3.2 on 2021-08-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0064_auto_20210803_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karaitesbookasarray',
            options={'ordering': ('book', 'ref_chapter', 'paragraph_number'), 'verbose_name_plural': 'Karaites book text as array'},
        ),
        migrations.RemoveField(
            model_name='karaitesbookasarray',
            name='page',
        ),
        migrations.AddField(
            model_name='karaitesbookasarray',
            name='ref_chapter',
            field=models.CharField(default='', max_length=50, verbose_name='Reference/Chapter'),
        ),
    ]
