# Generated by Django 3.2 on 2021-08-03 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0065_auto_20210803_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOfContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject, chapter , sheet ...')),
                ('start_paragraph', models.IntegerField(default=0)),
                ('karaite_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaites.karaitesbookdetails', verbose_name='Karaite book')),
            ],
            options={
                'verbose_name_plural': 'Table of contents',
            },
        ),
    ]
