# Generated by Django 3.2 on 2021-08-03 19:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0066_tableofcontents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='references',
            options={'verbose_name_plural': 'Karaites Bible references.'},
        ),
        migrations.AlterModelOptions(
            name='tableofcontents',
            options={'verbose_name_plural': 'Karaites  table of contents'},
        ),
        migrations.AlterField(
            model_name='tableofcontents',
            name='subject',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None),
        ),
    ]
