# Generated by Django 4.0.4 on 2022-11-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0066_remove_bookasarray_end_ms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookasarrayaudio',
            options={'ordering': ('book', 'chapter', 'verse', 'start'), 'verbose_name_plural': 'Biblical books audio'},
        ),
        migrations.RenameField(
            model_name='bookasarrayaudio',
            old_name='character',
            new_name='chapter',
        ),
    ]
