# Generated by Django 4.0.4 on 2022-11-08 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0067_alter_bookasarrayaudio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookasarrayaudio',
            name='char_per_second',
        ),
        migrations.CreateModel(
            name='Parsha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Order', verbose_name='Order')),
                ('parsha_he', models.CharField(blank=True, default='', help_text='Parsha', max_length=50, verbose_name='Parsha')),
                ('parsha_en', models.CharField(help_text='Parsha in English', max_length=50, verbose_name='Parsha in English')),
                ('parsha_portion', models.CharField(help_text='Parsha portion', max_length=20, verbose_name='Parsha portion')),
                ('first_reading', models.CharField(help_text='First reading', max_length=30, verbose_name='First reading')),
                ('first_description', models.TextField(help_text='First reading description', null=True, verbose_name='First reading description')),
                ('second_reading', models.CharField(help_text='Second reading', max_length=30, verbose_name='Second reading')),
                ('second_description', models.TextField(help_text='Second reading description', null=True, verbose_name='Second reading description')),
                ('third_reading', models.CharField(help_text='Third reading', max_length=30, verbose_name='Third reading')),
                ('third_description', models.TextField(help_text='Third reading description', null=True, verbose_name='Third reading description')),
                ('fourth_reading', models.CharField(help_text='Fourth reading', max_length=30, verbose_name='Fourth reading')),
                ('fourth_description', models.TextField(help_text='Fourth reading description', null=True, verbose_name='Fourth reading description')),
                ('fifth_reading', models.CharField(help_text='Fifth reading', max_length=30, verbose_name='Fifth reading')),
                ('fifth_description', models.TextField(help_text='Fifth reading description', null=True, verbose_name='Fifth reading description')),
                ('sixth_reading', models.CharField(help_text='Sixth reading', max_length=30, verbose_name='Sixth reading')),
                ('sixth_description', models.TextField(help_text='Sixth reading description', null=True, verbose_name='Sixth reading description')),
                ('seventh_reading', models.CharField(help_text='Seventh reading', max_length=30, verbose_name='Seventh reading')),
                ('seventh_description', models.TextField(help_text='Seventh reading description', null=True, verbose_name='Seventh reading description')),
                ('book', models.ForeignKey(help_text='Book', on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.organization', verbose_name='Book')),
            ],
            options={
                'verbose_name_plural': " Parsha's",
                'ordering': ('order',),
            },
        ),
    ]
