# Generated by Django 3.2 on 2021-08-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0067_auto_20210803_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karaitesbookasarray',
            options={'ordering': ('paragraph_number', 'book', 'ref_chapter'), 'verbose_name_plural': 'Karaites book text as array'},
        ),
        migrations.AlterModelOptions(
            name='tableofcontents',
            options={'ordering': ('subject',), 'verbose_name_plural': 'Karaites  table of contents'},
        ),
    ]
