# Generated by Django 4.0.4 on 2022-11-08 21:32

from django.db import migrations, models
import karaites.validatores.validators


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0068_remove_bookasarrayaudio_char_per_second_parsha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parsha',
            options={'ordering': ('order',), 'verbose_name_plural': "Parsha's"},
        ),
        migrations.AlterField(
            model_name='bookasarrayaudio',
            name='end',
            field=models.CharField(default='00:00:00.000', help_text='End time', max_length=12, validators=[karaites.validatores.validators.validate_time], verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='bookasarrayaudio',
            name='end_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bookasarrayaudio',
            name='start',
            field=models.CharField(default='00:00:00.000', help_text='Start time', max_length=12, validators=[karaites.validatores.validators.validate_time], verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='bookasarrayaudio',
            name='start_ms',
            field=models.FloatField(default=0.0),
        ),
    ]
