# Generated by Django 3.2 on 2021-08-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0068_auto_20210804_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='references',
            name='bible_book',
        ),
        migrations.AddField(
            model_name='references',
            name='bible_ref',
            field=models.CharField(default='', max_length=40, verbose_name='Bible reference'),
        ),
    ]
