# Generated by Django 3.2 on 2021-08-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0069_auto_20210804_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='references',
            name='bible_ref',
        ),
        migrations.AddField(
            model_name='references',
            name='bible_ref_en',
            field=models.CharField(default='', max_length=40, verbose_name='ref. English'),
        ),
        migrations.AddField(
            model_name='references',
            name='bible_ref_he',
            field=models.CharField(default='', max_length=40, verbose_name='ref. Hebrew'),
        ),
    ]
