# Generated by Django 4.0.4 on 2022-11-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0069_alter_parsha_options_alter_bookasarrayaudio_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsha',
            name='fifth_description',
            field=models.TextField(blank=True, help_text='Fifth reading description', null=True, verbose_name='Fifth reading description'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='fifth_reading',
            field=models.CharField(blank=True, help_text='Fifth reading', max_length=30, null=True, verbose_name='Fifth reading'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='first_description',
            field=models.TextField(blank=True, help_text='First reading description', null=True, verbose_name='First reading description'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='first_reading',
            field=models.CharField(blank=True, help_text='First reading', max_length=30, null=True, verbose_name='First reading'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='fourth_description',
            field=models.TextField(blank=True, help_text='Fourth reading description', null=True, verbose_name='Fourth reading description'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='fourth_reading',
            field=models.CharField(blank=True, help_text='Fourth reading', max_length=30, null=True, verbose_name='Fourth reading'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='parsha_he',
            field=models.CharField(help_text='Parsha', max_length=50, verbose_name='Parsha'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='second_description',
            field=models.TextField(blank=True, help_text='Second reading description', null=True, verbose_name='Second reading description'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='second_reading',
            field=models.CharField(blank=True, help_text='Second reading', max_length=30, null=True, verbose_name='Second reading'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='seventh_description',
            field=models.TextField(blank=True, help_text='Seventh reading description', null=True, verbose_name='Seventh reading description'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='seventh_reading',
            field=models.CharField(blank=True, help_text='Seventh reading', max_length=30, null=True, verbose_name='Seventh reading'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='sixth_description',
            field=models.TextField(blank=True, help_text='Sixth reading description', null=True, verbose_name='Sixth reading description'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='sixth_reading',
            field=models.CharField(blank=True, help_text='Sixth reading', max_length=30, null=True, verbose_name='Sixth reading'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='third_description',
            field=models.TextField(blank=True, help_text='Third reading description', null=True, verbose_name='Third reading description'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='third_reading',
            field=models.CharField(blank=True, help_text='Third reading', max_length=30, null=True, verbose_name='Third reading'),
        ),
    ]
