# Generated by Django 4.0.4 on 2022-11-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0070_alter_parsha_fifth_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsha',
            name='fifth_reading',
            field=models.CharField(help_text='Fifth reading', max_length=30, verbose_name='Fifth reading'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='first_reading',
            field=models.CharField(default='', help_text='First reading', max_length=30, verbose_name='First reading'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='fourth_reading',
            field=models.CharField(default='fill', help_text='Fourth reading', max_length=30, verbose_name='Fourth reading'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parsha',
            name='second_reading',
            field=models.CharField(default='', help_text='Second reading', max_length=30, verbose_name='Second reading'),
        ),
        migrations.AlterField(
            model_name='parsha',
            name='seventh_reading',
            field=models.CharField(default='fill', help_text='Seventh reading', max_length=30, verbose_name='Seventh reading'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parsha',
            name='sixth_reading',
            field=models.CharField(default='fill', help_text='Sixth reading', max_length=30, verbose_name='Sixth reading'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parsha',
            name='third_reading',
            field=models.CharField(default='fill', help_text='Third reading', max_length=30, verbose_name='Third reading'),
            preserve_default=False,
        ),
    ]
