# Generated by Django 3.2 on 2021-08-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0070_auto_20210804_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktext',
            name='book',
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
        migrations.RemoveField(
            model_name='karaitesbooktext',
            name='book',
        ),
        migrations.DeleteModel(
            name='BookText',
        ),
        migrations.DeleteModel(
            name='KaraitesBookText',
        ),
    ]
