# Generated by Django 3.2 on 2021-08-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0071_auto_20210805_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableofcontents',
            options={'ordering': ('start_paragraph',), 'verbose_name_plural': 'Karaites  table of contents'},
        ),
        migrations.AddField(
            model_name='organization',
            name='total_verses',
            field=models.IntegerField(default=0),
        ),
    ]
