# Generated by Django 3.2 on 2021-09-06 17:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0073_alter_bookasarray_book_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='references',
            name='foot_notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None),
        ),
    ]
