# Generated by Django 4.0.4 on 2022-11-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0073_bookasarrayaudio_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='audio_file',
            field=models.FileField(help_text='Audiobook file', upload_to='audio-books/', verbose_name='Audiobook file'),
        ),
    ]
