# Generated by Django 4.0.4 on 2022-11-19 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0074_alter_audiobook_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookasarrayaudio',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.organization', verbose_name='Book'),
        ),
    ]
