# Generated by Django 3.2 on 2021-09-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0074_references_foot_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookasarray',
            name='text_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bookasarray',
            name='text_he',
            field=models.TextField(default=''),
        ),
    ]
