# Generated by Django 3.2 on 2021-09-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0075_auto_20210924_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullTextSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('text_english', models.TextField(default='')),
                ('text_hebrew', models.TextField(default='')),
                ('dont_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Full text search',
            },
        ),
        migrations.RemoveField(
            model_name='bookasarray',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='bookasarray',
            name='text_he',
        ),
    ]
