# Generated by Django 3.2 on 2021-09-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0076_auto_20210924_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fulltextsearch',
            old_name='dont_delete',
            new_name='delete',
        ),
    ]
