# Generated by Django 3.2 on 2021-09-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0077_rename_dont_delete_fulltextsearch_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulltextsearch',
            name='reference',
        ),
        migrations.AddField(
            model_name='fulltextsearch',
            name='reference_en',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fulltextsearch',
            name='reference_he',
            field=models.CharField(default='', max_length=100),
        ),
    ]
