# Generated by Django 4.1 on 2023-04-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0077_liturgydetails_display'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liturgybook',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='liturgybook',
            name='line_number',
            field=models.IntegerField(default=0, help_text='Line Number', verbose_name='Line Number'),
        ),
        migrations.AlterUniqueTogether(
            name='liturgybook',
            unique_together={('book', 'song', 'line_number')},
        ),
    ]
