# Generated by Django 3.2 on 2021-09-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0078_auto_20210924_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fulltextsearch',
            old_name='text_english',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='fulltextsearch',
            old_name='text_hebrew',
            new_name='text_he',
        ),
    ]
