# Generated by Django 3.2 on 2021-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0079_auto_20210924_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.CharField(db_index=True, max_length=30)),
            ],
        ),
    ]
