# Generated by Django 4.1 on 2023-04-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0079_alter_liturgydetails_occasion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liturgybook',
            options={'ordering': ('book__english_name', 'song__song_title', 'line_number'), 'verbose_name_plural': 'Liturgy Books'},
        ),
    ]
