# Generated by Django 3.2 on 2021-09-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0080_autocomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocomplete',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
