# Generated by Django 4.1 on 2023-06-05 19:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0081_liturgydetails_author_liturgydetails_book_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookasarray',
            name='line_number',
            field=models.IntegerField(default=0, help_text='Line Number', verbose_name='Line Number'),
        ),
        migrations.AddField(
            model_name='karaitesbookasarray',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audiobook', to='karaites.songs'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='better_book',
            field=models.BooleanField(default=False, help_text='This field is used to inform if the books is better book', verbose_name='Better book'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='better_intro',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=list, size=None),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='better_toc',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=list, size=None),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='display',
            field=models.CharField(default='1', help_text='1) Hebrew on Left. Transliteration on right.                                       Each verse has its translation below it. ', max_length=1, verbose_name='Display'),
        ),
    ]
