# Generated by Django 3.2 on 2021-09-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0081_autocomplete_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocomplete',
            name='word_count',
            field=models.IntegerField(default=1),
        ),
    ]
