# Generated by Django 3.2 on 2021-09-29 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0082_alter_autocomplete_word_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autocomplete',
            options={'ordering': ('word_en',)},
        ),
    ]
