# Generated by Django 3.2 on 2021-10-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0083_alter_autocomplete_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocomplete',
            name='word_en',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
