# Generated by Django 4.1 on 2023-07-17 19:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0084_alter_karaitesbetterbooksproxy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='better_intro',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='better_toc',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_source',
            field=models.FileField(blank=True, default='', help_text='This field is used to store the source of the book', upload_to='books/', verbose_name='Book Source '),
        ),
    ]
