# Generated by Django 3.2 on 2021-10-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0084_alter_autocomplete_word_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocomplete',
            name='word_en',
            field=models.CharField(db_index=True, max_length=60),
        ),
    ]
