# Generated by Django 3.2 on 2021-11-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0086_alter_autocomplete_word_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autocomplete',
            options={'ordering': ('word_en', '-word_count')},
        ),
    ]
