# Generated by Django 3.2 on 2021-11-08 20:08

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0087_alter_autocomplete_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulltextsearch',
            name='text_en_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='fulltextsearch',
            name='text_he_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='fulltextsearch',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_en_search'], name='karaites_fu_text_en_38b800_gin'),
        ),
    ]
