# Generated by Django 3.2 on 2021-11-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0089_create_search_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocomplete',
            name='classification',
            field=models.CharField(choices=[('B', 'Book'), ('V', 'Verse')], default='V', max_length=1),
        ),
    ]
