# Generated by Django 3.2 on 2021-11-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0090_autocomplete_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='bible_ref_en',
            field=models.CharField(default='', max_length=60, verbose_name='ref. English'),
        ),
    ]
