# Generated by Django 3.2 on 2021-11-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0091_alter_references_bible_ref_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='bible_ref_he',
            field=models.CharField(default='', max_length=60, verbose_name='ref. Hebrew'),
        ),
    ]
