# Generated by Django 3.2 on 2021-11-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0093_auto_20211126_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='bible_ref_en',
            field=models.TextField(default='', verbose_name='ref. English'),
        ),
        migrations.AlterField(
            model_name='references',
            name='bible_ref_he',
            field=models.TextField(default='', verbose_name='ref. Hebrew'),
        ),
    ]
