# Generated by Django 3.2 on 2021-11-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0094_auto_20211126_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='bible_ref_en',
            field=models.CharField(default='', max_length=40, verbose_name='ref. English'),
        ),
        migrations.AlterField(
            model_name='references',
            name='bible_ref_he',
            field=models.CharField(default='', max_length=40, verbose_name='ref. Hebrew'),
        ),
    ]
