# Generated by Django 3.2 on 2021-12-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0095_auto_20211126_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_classification',
            field=models.CharField(choices=[('01', 'Prayer'), ('02', 'Blessing'), ('03', 'Karaite Jewish practice'), ('04', 'Egyptian Karaite Tradition'), ('05', 'Aliyyot Poems'), ('06', 'Recipes'), ('07', 'Biblical verses'), ('08', 'Poems')], max_length=2, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh'), (3, 'Halakhah'), (4, 'Liturgy'), (5, 'Polemic')], default=0, verbose_name='Law'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh'), (3, 'Halakhah'), (4, 'Liturgy'), (5, 'Polemic')], default=0, verbose_name='Law'),
        ),
    ]
