# Generated by Django 3.2 on 2021-12-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0096_auto_20211229_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name_he',
            field=models.CharField(default='', max_length=50),
        ),
    ]
