# Generated by Django 3.2 on 2021-12-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0097_author_name_he'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='introduction',
            field=models.TextField(default=''),
        ),
    ]
