# Generated by Django 3.2 on 2021-12-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0098_karaitesbookdetails_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name_he',
            field=models.CharField(default='', max_length=100),
        ),
    ]
