# Generated by Django 3.2 on 2022-01-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0099_alter_author_name_he'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='karaitesbookdetails',
            unique_together={('book_title', 'author', 'introduction')},
        ),
    ]
