# Generated by Django 3.2 on 2022-01-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0100_alter_karaitesbookdetails_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='karaitesbookdetails',
            unique_together={('book_title', 'author')},
        ),
    ]
