# Generated by Django 3.2 on 2022-01-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0101_alter_karaitesbookdetails_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='book_title_unslug',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
