# Generated by Django 3.2 on 2022-01-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0102_karaitesbookdetails_book_title_unslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh'), (2, 'Talmud'), (3, 'Halakhah'), (4, 'Liturgy'), (5, 'Polemic')], default=0, verbose_name='Law'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh'), (2, 'Talmud'), (3, 'Halakhah'), (4, 'Liturgy'), (5, 'Polemic')], default=0, verbose_name='Law'),
        ),
    ]
