# Generated by Django 3.2 on 2022-02-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0103_auto_20220125_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_classification',
            field=models.CharField(choices=[('01', 'Prayers'), ('02', 'Blessing'), ('03', 'Karaite Jewish practice'), ('04', 'Egyptian Karaite Tradition'), ('05', 'Aliyyot Poems'), ('06', 'Recipes'), ('07', 'Biblical verses'), ('08', 'Poems'), ('09', 'PDFs'), ('01', 'Prayers'), ('10', 'Havdala Songs'), ('11', 'Shabbat Songs'), ('12', 'Wedding Songs'), ('13', 'Supplemental Readings for specific Torah portions')], max_length=2, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh'), (2, 'Talmud'), (3, 'Halakhah'), (4, 'Liturgy'), (5, 'Polemics'), (6, 'Songs'), (7, 'Prayers')], default=0, verbose_name='Law'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh'), (2, 'Talmud'), (3, 'Halakhah'), (4, 'Liturgy'), (5, 'Polemics'), (6, 'Songs'), (7, 'Prayers')], default=0, verbose_name='Law'),
        ),
    ]
