# Generated by Django 3.2 on 2022-02-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0104_auto_20220207_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='references',
            name='error',
            field=models.CharField(choices=[('00', 'Verse number to big'), ('01', 'Chapter number to big')], default='', max_length=2, verbose_name='error'),
        ),
    ]
