# Generated by Django 3.2 on 2022-02-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0105_references_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='error',
            field=models.CharField(choices=[('--', '--'), ('00', 'Verse number to big.'), ('01', 'Chapter number to big.'), ('02', 'Bible book does not exist!')], default='', max_length=2, verbose_name='error'),
        ),
    ]
