# Generated by Django 3.2 on 2022-03-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0106_alter_references_error'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karaitesbookdetails',
            options={'ordering': ('book_title_en', 'author'), 'verbose_name_plural': 'Karaites book details'},
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='book_title_en',
            field=models.CharField(default='', max_length=100, verbose_name='Title English'),
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='book_title_he',
            field=models.CharField(default='', max_length=100, verbose_name='Title Hebrew'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_classification',
            field=models.CharField(choices=[('10', 'Havdala Songs'), ('20', 'Prayers'), ('30', 'Shabbat Songs'), ('40', 'Supplemental Readings for specific Torah portions'), ('50', 'Wedding Songs'), ('60', 'Polemic'), ('70', 'Test'), ('80', 'Other')], max_length=2, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_language',
            field=models.CharField(choices=[('en', 'English'), ('he', 'Hebrew'), ('en,he', 'Hebrew/English')], max_length=8, verbose_name='Book language'),
        ),
        migrations.AlterUniqueTogether(
            name='karaitesbookdetails',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='karaitesbookdetails',
            name='book_title',
        ),
    ]
