# Generated by Django 3.2 on 2022-02-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0106_alter_references_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_classification',
            field=models.CharField(choices=[('10', 'Havdala Songs'), ('20', 'Prayers'), ('30', 'Shabbat Songs'), ('40', 'Supplemental Readings for specific Torah portions'), ('50', 'Wedding Songs'), ('60', 'Polemic'), ('70', 'Test'), ('80', 'Other')], max_length=2, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_language',
            field=models.CharField(choices=[('en', 'English'), ('en,in', 'English with introduction'), ('he', 'Hebrew'), ('he,in', 'Hebrew with introduction'), ('en,he,in', 'English/Hebrew/ with Introduction')], max_length=8, verbose_name='Book language'),
        ),
    ]
