# Generated by Django 3.2 on 2022-03-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0108_auto_20220303_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbookasarray',
            name='ref_chapter',
            field=models.CharField(default='', max_length=250, verbose_name='Reference/Chapter'),
        ),
    ]
