# Generated by Django 3.2 on 2022-03-04 14:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0109_alter_karaitesbookasarray_ref_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbookasarray',
            name='book_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=['', 0, ''], size=None),
        ),
    ]
