# Generated by Django 3.2 on 2022-03-04 14:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0110_alter_karaitesbookasarray_book_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbookasarray',
            name='book_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=list, size=None),
        ),
    ]
