# Generated by Django 3.2 on 2022-03-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0111_alter_karaitesbookasarray_book_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_classification',
            field=models.CharField(choices=[('10', 'Havdala Songs'), ('20', 'Prayers'), ('30', 'Shabbat Songs'), ('40', 'Supplemental Readings for specific Torah portions'), ('50', 'Wedding Songs'), ('55', 'Poetry'), ('60', 'Polemic'), ('70', 'Test'), ('80', 'Comments'), ('90', 'Other')], max_length=2, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh'), (2, 'Talmud'), (3, 'Halakhah'), (4, 'Liturgy'), (5, 'Polemics'), (6, 'Songs'), (7, 'Prayers'), (8, 'Comments'), (9, 'Poetry (Non-Liturgical)')], default=0, verbose_name='Law'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh'), (2, 'Talmud'), (3, 'Halakhah'), (4, 'Liturgy'), (5, 'Polemics'), (6, 'Songs'), (7, 'Prayers'), (8, 'Comments'), (9, 'Poetry (Non-Liturgical)')], default=0, verbose_name='Law'),
        ),
    ]
