# Generated by Django 3.2 on 2022-03-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0112_auto_20220307_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaitesbookasarray',
            name='ref_chapter',
            field=models.CharField(default='', max_length=260, verbose_name='Reference/Chapter'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_classification',
            field=models.CharField(choices=[('00', 'Unknown'), ('10', 'Havdala Songs'), ('20', 'Prayers'), ('30', 'Shabbat Songs'), ('40', 'Supplemental Readings for specific Torah portions'), ('50', 'Wedding Songs'), ('55', 'Poetry'), ('60', 'Polemic'), ('70', 'Test'), ('80', 'Comments'), ('90', 'Other')], max_length=2, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_language',
            field=models.CharField(choices=[('en', 'English'), ('he', 'Hebrew'), ('en,he', 'Hebrew/English'), ('ja', 'Judeo-Arabic')], max_length=8, verbose_name='Book language'),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh'), (2, 'Talmud'), (3, 'Halakhah'), (4, 'Liturgy'), (5, 'Polemics'), (6, 'Songs'), (7, 'Prayers'), (8, 'Comments'), (9, 'Poetry (Non-Liturgical)'), (10, 'Other')], default=0, verbose_name='Law'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='first_level',
            field=models.IntegerField(choices=[(1, 'Tanakh'), (2, 'Talmud'), (3, 'Halakhah'), (4, 'Liturgy'), (5, 'Polemics'), (6, 'Songs'), (7, 'Prayers'), (8, 'Comments'), (9, 'Poetry (Non-Liturgical)'), (10, 'Other')], default=0, verbose_name='Law'),
        ),
    ]
