# Generated by Django 3.2 on 2022-03-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0114_karaitesbookdetails_book_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karaitesbookdetails',
            name='book_type',
        ),
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='table_book',
            field=models.BooleanField(default=False),
        ),
    ]
