# Generated by Django 3.2 on 2022-03-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0115_auto_20220309_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='columns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='karaitesbookdetails',
            name='book_classification',
            field=models.CharField(choices=[('00', 'Unknown'), ('10', 'Havdala Songs'), ('15', 'Passover Songs'), ('18', 'Purim Songs'), ('20', 'Prayers'), ('30', 'Shabbat Songs'), ('40', 'Supplemental Readings for specific Torah portions'), ('50', 'Wedding Songs'), ('55', 'Poetry'), ('60', 'Polemic'), ('70', 'Test'), ('80', 'Comments'), ('90', 'Other')], max_length=2, verbose_name='Classification'),
        ),
    ]
