# Generated by Django 3.2 on 2022-03-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0116_auto_20220320_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='columns_order',
            field=models.CharField(default='', max_length=10),
        ),
    ]
