# Generated by Django 3.2 on 2022-03-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0117_karaitesbookdetails_columns_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='toc_columns',
            field=models.CharField(default='', max_length=10),
        ),
    ]
