# Generated by Django 3.2 on 2022-03-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0118_karaitesbookdetails_toc_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='direction',
            field=models.CharField(default='rtl', max_length=3),
        ),
    ]
