# Generated by Django 3.2 on 2022-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0119_karaitesbookdetails_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='remove_class',
            field=models.CharField(default='', max_length=100),
        ),
    ]
