# Generated by Django 3.2 on 2022-03-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0120_karaitesbookdetails_remove_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='remove_tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
