# Generated by Django 3.2 on 2022-03-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0121_karaitesbookdetails_remove_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaitesbookdetails',
            name='multi_tables',
            field=models.BooleanField(default=False),
        ),
    ]
