# Generated by Django 3.2 on 2022-03-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0122_karaitesbookdetails_multi_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulltextsearch',
            name='path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
