# Generated by Django 3.2 on 2022-04-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0123_fulltextsearch_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltextsearch',
            name='path',
            field=models.CharField(default='', max_length=20),
        ),
    ]
