# Generated by Django 3.2 on 2022-04-13 16:22

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0124_alter_fulltextsearch_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullTextSearchHebrew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=20)),
                ('reference_he', models.CharField(default='', max_length=100)),
                ('text_he', models.TextField(default='')),
                ('text_he_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Full text search Hebrew',
            },
        ),
        migrations.AlterModelOptions(
            name='fulltextsearch',
            options={'verbose_name_plural': 'Full text search English'},
        ),
        migrations.RemoveField(
            model_name='fulltextsearch',
            name='reference_he',
        ),
        migrations.RemoveField(
            model_name='fulltextsearch',
            name='text_he',
        ),
        migrations.RemoveField(
            model_name='fulltextsearch',
            name='text_he_search',
        ),
        migrations.AddIndex(
            model_name='fulltextsearchhebrew',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_he_search'], name='karaites_fu_text_he_f8de45_gin'),
        ),
    ]
