# Generated by Django 3.2 on 2022-04-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0125_auto_20220413_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulltextsearchhebrew',
            name='reference_en',
            field=models.CharField(default='', max_length=100),
        ),
    ]
