# Generated by Django 3.2 on 2022-04-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0126_fulltextsearchhebrew_reference_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfHebrewWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_collation='he_IL.UTF-8', db_index=True, max_length=20, verbose_name='Hebrew word')),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'List of unique Hebrew words',
            },
        ),
        migrations.AlterField(
            model_name='fulltextsearchhebrew',
            name='reference_en',
            field=models.CharField(db_collation='he_IL.UTF-8', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fulltextsearchhebrew',
            name='reference_he',
            field=models.CharField(db_collation='he_IL.UTF-8', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fulltextsearchhebrew',
            name='text_he',
            field=models.TextField(db_collation='he_IL.UTF-8', default=''),
        ),
    ]
