# Generated by Django 3.2 on 2022-04-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0127_auto_20220414_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofhebrewwords',
            name='word',
            field=models.CharField(db_collation='he_IL.UTF-8', db_index=True, max_length=40, verbose_name='Hebrew word'),
        ),
    ]
