# Generated by Django 3.2 on 2022-04-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0128_alter_listofhebrewwords_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='HebrewIndexSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_collation='he_IL.UTF-8', default='', max_length=100, verbose_name='Document reference')),
                ('list_of_words', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Document/word')),
                ('density', models.IntegerField(default=0, verbose_name='Density')),
            ],
            options={
                'verbose_name_plural': 'Words by Document',
            },
        ),
    ]
