# Generated by Django 3.2 on 2022-04-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0129_hebrewindexsearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hebrewindexsearch',
            old_name='list_of_words',
            new_name='word',
        ),
    ]
