# Generated by Django 3.2 on 2022-04-18 14:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0130_rename_list_of_words_hebrewindexsearch_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hebrewindexsearch',
            name='density',
        ),
        migrations.RemoveField(
            model_name='hebrewindexsearch',
            name='reference',
        ),
        migrations.AddField(
            model_name='hebrewindexsearch',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='hebrewindexsearch',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='karaites.listofhebrewwords'),
        ),
    ]
