# Generated by Django 3.2 on 2022-04-18 15:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0131_auto_20220418_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvertedIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_collation='he_IL.UTF-8', db_index=True, max_length=40, verbose_name='Hebrew word')),
                ('count', models.IntegerField(default=0, verbose_name='Count in all documents')),
                ('documents', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None, verbose_name='list of documents')),
                ('count_by_document', models.IntegerField(default=0, verbose_name='count by document')),
            ],
            options={
                'verbose_name_plural': 'Inverted index',
            },
        ),
        migrations.DeleteModel(
            name='HebrewIndexSearch',
        ),
        migrations.DeleteModel(
            name='ListOfHebrewWords',
        ),
    ]
