# Generated by Django 3.2 on 2022-04-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0132_auto_20220418_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invertedindex',
            name='count_by_document',
        ),
    ]
