# Generated by Django 3.2 on 2022-04-18 16:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0133_remove_invertedindex_count_by_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='invertedindex',
            name='count_by_document',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None, verbose_name='count by document'),
        ),
    ]
