# Generated by Django 3.2 on 2022-04-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0134_invertedindex_count_by_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='invertedindex',
            name='word_as_in_text',
            field=models.CharField(db_collation='he_IL.UTF-8', db_index=True, default='', max_length=40, verbose_name='Hebrew word with niqkud and/or cantilation'),
        ),
    ]
