# Generated by Django 3.2 on 2022-04-18 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0136_alter_invertedindex_word_as_in_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invertedindex',
            name='word_as_in_text',
        ),
    ]
