# Generated by Django 3.2 on 2022-04-18 22:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0137_remove_invertedindex_word_as_in_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='invertedindex',
            name='word_as_in_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(db_collation='he_IL.UTF-8', default='', max_length=40), blank=True, default=list, null=True, size=None, verbose_name='Word as in text'),
        ),
    ]
