# Generated by Django 3.2 on 2022-04-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaites', '0138_invertedindex_word_as_in_text'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fulltextsearchhebrew',
            name='karaites_fu_text_he_f8de45_gin',
        ),
        migrations.RemoveField(
            model_name='fulltextsearchhebrew',
            name='text_he_search',
        ),
        migrations.AlterField(
            model_name='fulltextsearchhebrew',
            name='reference_en',
            field=models.CharField(db_collation='he_IL.UTF-8', db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fulltextsearchhebrew',
            name='reference_he',
            field=models.CharField(db_collation='he_IL.UTF-8', db_index=True, default='', max_length=100),
        ),
    ]
