# constant for new karaites experiment


LANGUAGES = [
    ('en', 'English'),
    ('he', 'Hebrew'),
    ('en/he', 'English/Hebrew'),
]

BOOK_CLASSIFICATION = [
    ('01', 'Prayer'),
    ('02', 'Blessing'),
    ('03', 'Karaite Jewish practice'),
    ('04', 'Egyptian Karaite Tradition'),
    ('05', 'Poems'),
    ('06', 'Recipes')
]

FIRST_LEVEL = [
    (1, 'Tanakh'),
    # (2, 'Talmud'),
    (3, 'Halakhah'),
]

SECOND_LEVEL = [
    (1, 'Torah'),
    (2, 'Prophets'),
    (3, 'Writings')
]

ENGLISH_STOP_WORDS = {
    'i': '',
    'me': '',
    'my': '',
    'myself': '',
    'we': '',
    'our': '',
    'ours': '',
    'ourselves': '',
    'you': '',
    'your': '',
    'yours': '',
    'yourself': '',
    'yourselves': '',
    'he': '',
    'him': '',
    'his': '',
    'himself': '',
    'she': '',
    'her': '',
    'hers': '',
    'herself': '',
    'it': '',
    'its': '',
    'itself': '',
    'they': '',
    'them': '',
    'their': '',
    'theirs': '',
    'themselves': '',
    'what': '',
    'which': '',
    'who': '',
    'whom': '',
    'this': '',
    'that': '',
    'these': '',
    'those': '',
    'am': '',
    'is': '',
    'are': '',
    'was': '',
    'were': '',
    'be': '',
    'been': '',
    'being': '',
    'have': '',
    'has': '',
    'had': '',
    'having': '',
    'do': '',
    'does': '',
    'did': '',
    'doing': '',
    'a': '',
    'an': '',
    'the': '',
    'and': '',
    'but': '',
    'if': '',
    'or': '',
    'because': '',
    'as': '',
    'until': '',
    'while': '',
    'of': '',
    'at': '',
    'by': '',
    'for': '',
    'with': '',
    'about': '',
    'against': '',
    'between': '',
    'into': '',
    'through': '',
    'during': '',
    'before': '',
    'after': '',
    'above': '',
    'below': '',
    'to': '',
    'from': '',
    'up': '',
    'down': '',
    'in': '',
    'out': '',
    'on': '',
    'off': '',
    'over': '',
    'under': '',
    'again': '',
    'further': '',
    'then': '',
    'once': '',
    'here': '',
    'there': '',
    'when': '',
    'where': '',
    'why': '',
    'how': '',
    'all': '',
    'any': '',
    'both': '',
    'each': '',
    'few': '',
    'more': '',
    'most': '',
    'other': '',
    'some': '',
    'such': '',
    'no': '',
    'nor': '',
    'not': '',
    'only': '',
    'own': '',
    'same': '',
    'so': '',
    'than': '',
    'too': '',
    'very': '',
    's': '',
    't': '',
    'can': '',
    'will': '',
    'just': '',
    'don': '',
    'should': '',
    'now': ''
}

HEBREW_STOP_WORDS = {

}

AUTOCOMPLETE_TYPE = [
    ('B', 'Book'),
    ('V', 'Verse')
]

BIBLE_BOOKS_NAMES = {
    'בראשית': 'Genesis',
    'שמות': 'Exodus',
    'ויקרא': 'Leviticus',
    'במדבר': 'Numbers',
    'דברים': 'Deuteronomy',
    'עמוס': 'Amos',
    'יחזקאל': 'Ezekiel',
    'חבקוק': 'Habakkuk',
    'חגי': 'Haggai',
    'הושע': 'Hosea',
    'מלכים א': 'I Kings',
    'שמואל א': 'I Samuel',
    'מלכים ב': 'II Kings',
    'שמואל ב': 'II Samuel',
    'ישעיה': 'Isaiah',
    'ישעיהו': 'Isaiah',  # typo ?
    'ירמיה': 'Jeremiah',
    'ירמיהו': 'Jeremiah',  # typo ?
    'יואל': 'Joel',
    'יונה': 'Jonah',
    'יהושע': 'Joshua',
    'שופטים': 'Judges',
    'מלאכי': 'Malachi',
    'מיכה': 'Micah',
    'נחום': 'Nahum',
    'עובדיה': 'Obadiah',
    'זכריה': 'Zechariah',
    'צפניה': 'Zephaniah',
    'דניאל': 'Daniel',
    'קהלת': 'Ecclesiastes',
    'אסתר': 'Esther',
    'עזרא': 'Ezra',
    'דברי הימים א': 'I Chronicles',
    'דברי הימים ב': 'II Chronicles',
    'איוב': 'Job',
    'איכה': 'Lamentations',
    'נחמיה': 'Nehemiah',
    'משלי': 'Proverbs',
    'תהלים': 'Psalms',  # possible typo
    'תהילים': 'Psalms',
    'רות': 'Ruth',
    'שיר השירים': 'Song of Songs'
}
