# constant for new karaites experiment


LANGUAGES = [
    ('en', 'English'),
    ('he', 'Hebrew'),
    ('he-en', 'Hebrew-English'),
    ('ja', 'Judeo-Arabic'),
]

LANGUAGES_DICT = {'en': "English",
                  'he': "Hebrew",
                  'ja': 'Judeo-Arabic',
                  # this means a formatted table with hebrew and english
                  'he-en': 'Hebrew-English',
                  # technical "in" , "toc" are not a language,
                  # we use to process introduction files and table of contents files
                  "in": "Introduction",
                  'toc': "TOC"}


BOOK_CLASSIFICATION = [
    ('00', 'Unknown'),
    # liturgy
    ('10', 'Havdala Songs'),
    ('15', 'Passover Songs'),
    ('18', 'Purim Songs'),
    ('20', 'Prayers'),
    ('30', 'Shabbat Songs'),
    ('40', 'Supplemental Readings for specific Torah portions'),
    ('45', 'Tammuz/Av/Echa'),
    ('50', 'Wedding Songs'),
    # poetry
    ('55', 'Poetry'),
    # Polemic
    ('60', 'Polemic'),
    ('65', 'Exhortatory'),
    # test
    ('70', 'Test'),
    ('80', 'Comments'),
    # other
    ('90', 'Other'),

]
BOOK_CLASSIFICATION_DICT = dict(BOOK_CLASSIFICATION)

FIRST_LEVEL = [
    (1, 'Tanakh'),
    (2, 'Talmud'),
    (3, 'Halakhah'),
    (4, 'Liturgy'),
    (5, 'Polemics'),
    (6, 'Songs'),
    (7, 'Prayers'),
    (8, 'Comments'),
    (9, 'Poetry (Non-Liturgical)'),
    (10, 'Other'),
    (11, 'Exhortatory'),
]

FIRST_LEVEL_DICT = dict(FIRST_LEVEL)

SECOND_LEVEL = [
    (1, 'Torah'),
    (2, 'Prophets'),
    (3, 'Writings')
]

ENGLISH_STOP_WORDS = {
    'i': '',
    'me': '',
    'my': '',
    'myself': '',
    'we': '',
    'our': '',
    'ours': '',
    'ourselves': '',
    'you': '',
    'your': '',
    'yours': '',
    'yourself': '',
    'yourselves': '',
    'he': '',
    'him': '',
    'his': '',
    'himself': '',
    'she': '',
    'her': '',
    'hers': '',
    'herself': '',
    'it': '',
    'its': '',
    'itself': '',
    'they': '',
    'them': '',
    'their': '',
    'theirs': '',
    'themselves': '',
    'what': '',
    'which': '',
    'who': '',
    'whom': '',
    'this': '',
    'that': '',
    'these': '',
    'those': '',
    'am': '',
    'is': '',
    'are': '',
    'was': '',
    'were': '',
    'be': '',
    'been': '',
    'being': '',
    'have': '',
    'has': '',
    'had': '',
    'having': '',
    'do': '',
    'does': '',
    'did': '',
    'doing': '',
    'a': '',
    'an': '',
    'the': '',
    'and': '',
    'but': '',
    'if': '',
    'or': '',
    'because': '',
    'as': '',
    'until': '',
    'while': '',
    'of': '',
    'at': '',
    'by': '',
    'for': '',
    'with': '',
    'about': '',
    'against': '',
    'between': '',
    'into': '',
    'through': '',
    'during': '',
    'before': '',
    'after': '',
    'above': '',
    'below': '',
    'to': '',
    'from': '',
    'up': '',
    'down': '',
    'in': '',
    'out': '',
    'on': '',
    'off': '',
    'over': '',
    'under': '',
    'again': '',
    'further': '',
    'then': '',
    'once': '',
    'here': '',
    'there': '',
    'when': '',
    'where': '',
    'why': '',
    'how': '',
    'all': '',
    'any': '',
    'both': '',
    'each': '',
    'few': '',
    'more': '',
    'most': '',
    'other': '',
    'some': '',
    'such': '',
    'no': '',
    'nor': '',
    'not': '',
    'only': '',
    'own': '',
    'same': '',
    'so': '',
    'than': '',
    'too': '',
    'very': '',
    's': '',
    't': '',
    'can': '',
    'will': '',
    'just': '',
    'don': '',
    'should': '',
    'now': ''
}

HEBREW_STOP_WORDS = {

}

AUTOCOMPLETE_TYPE = [
    ('B', 'Book'),
    ('V', 'Verse')
]

BIBLE_BOOKS_NAMES = {
    'בראשית': 'Genesis',
    'שמות': 'Exodus',
    'ויקרא': 'Leviticus',
    'במדבר': 'Numbers',
    'דברים': 'Deuteronomy',
    'עמוס': 'Amos',
    'יחזקאל': 'Ezekiel',
    'חבקוק': 'Habakkuk',
    'חגי': 'Haggai',
    'הושע': 'Hosea',
    'מלכים א': 'I Kings',
    'שמואל א': 'I Samuel',
    'מלכים ב': 'II Kings',
    'שמואל ב': 'II Samuel',

    'ישעיהו': 'Isaiah',  # typo ?
    'ישעיה': 'Isaiah',
    'ירמיה': 'Jeremiah',
    'ירמיהו': 'Jeremiah',  # typo ?
    'יואל': 'Joel',
    'יונה': 'Jonah',
    'יהושע': 'Joshua',
    'שופטים': 'Judges',
    'מלאכי': 'Malachi',
    'מיכה': 'Micah',
    'נחום': 'Nahum',
    'עובדיה': 'Obadiah',
    'זכריה': 'Zechariah',
    'צפניה': 'Zephaniah',
    'דניאל': 'Daniel',
    'קהלת': 'Ecclesiastes',
    'אסתר': 'Esther',
    'עזרא': 'Ezra',
    'דברי הימים א': 'I Chronicles',
    'דברי הימים ב': 'II Chronicles',
    'איוב': 'Job',
    'איכה': 'Lamentations',
    'נחמיה': 'Nehemiah',
    'משלי': 'Proverbs',
    # 'תהליםקט': 'Psalms',
    # 'תהליםל': 'Psalms',
    'תהילים': 'Psalms',
    'רות': 'Ruth',
    'שיר השירים': 'Song of Songs'
}

REF_ERROR_CODE = [
    ('--', '--'),
    ('00', 'Verse number to big.'),
    ('01', 'Chapter number to big.'),
    ('02', 'Bible book does not exist!'),
]
